[DPEDE-1415] Added icon property to dropdown
CenturyLink/Chi pull request #1062
Opened 2024-02-29 14:58 UTC by wojciechwlodarczyklumen

2024-03-06 12:09 UTC, ASanchLumen commented
Hi @wojciechwlodarczyklumen! The branch has conflicts, please resolve!

2024-03-06 12:16 UTC, ASanchLumen commented on src/website/views/components/dropdown/_examples.pug
> +    | There is available property <code>icon</code> which allows to add an icon as the dropdown trigger.
Hi! Just some grammar stuff:

`There is an available property, <code>icon</code>, which allows adding an icon as the dropdown trigger.`

2024-03-06 12:21 UTC, ASanchLumen commented
Should this feature have visual tests @josecarlosgonzalezv?

2024-03-11 10:35 UTC, josecarlosgonzalezv requested changes

2024-03-12 10:58 UTC, ASanchLumen commented on src/documentation/pages/components-wip/dropdown/examples/_icon_trigger.vue
> +      button#example__dropdown-icon.chi-button.chi-dropdown__trigger.chi-dropdown__icon(aria-label="More options" data-tooltip="More options")
In vue docs we can use the web component. For portal theme, in the website documentation it's being used  `variant=flat`. In this docs you can access the selected theme with `selectedTheme = useSelectedTheme();` and use the right variant: `:variant="selectedTheme === 'portal' ? 'flat' : ''".

Code snippets should also reflect this change.

2024-03-12 10:59 UTC, ASanchLumen commented on src/website/views/components/dropdown/_examples.pug
> +    | There is available property <code>icon</code> which allows to add an icon as the dropdown trigger.
```suggestion
    | There is an available property, <code>icon</code>, which allows adding an icon as the dropdown trigger.
```

2024-03-12 11:01 UTC, ASanchLumen commented on src/documentation/pages/components-wip/dropdown/examples/_retain_selection.vue
> +      webcomponent: ``,
Codesnippet missing for web component

2024-03-12 11:02 UTC, ASanchLumen commented on src/documentation/pages/components-wip/dropdown/examples/_icon_trigger.vue
> +      webcomponent: ``,
codeSnippet missing for web component!

2024-03-12 11:02 UTC, ASanchLumen requested changes
Update docs, otherwise ok!

2024-03-12 16:33 UTC, josecarlosgonzalezv approved these changes

2024-03-12 16:38 UTC, jllr approved these changes

2024-03-12 16:41 UTC, ASanchLumen approved these changes

2024-03-12 16:42 UTC, merged