[FSDE-281] Add disable property for row to be unselectable
CenturyLink/Chi pull request #107
Opened 2021-07-14 16:05 UTC by aryaroudi

hey @janibolkvadze please review this!

2021-07-14 16:33 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-107/1/. :white_check_mark:

2021-07-14 16:33 UTC, SCMAUTO commented
You can check this PRs instance in https://c44b935de490a6baaaa215ce843c098208aea837-chi-pr.enterprise.ctl.io

2021-07-14 17:48 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-107/2/. :x:

2021-07-15 07:06 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-107/3/. :white_check_mark:

2021-07-15 07:06 UTC, SCMAUTO commented
You can check this PRs instance in https://c17d2a08be008d9d5f5e27ba0baeb731e10394df-chi-pr.enterprise.ctl.io

2021-07-15 09:57 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-107/4/. :x:

2021-07-15 10:19 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-107/5/. :white_check_mark:

2021-07-15 10:19 UTC, SCMAUTO commented
You can check this PRs instance in https://545682ed316e765b215a60a39892b015eb8cf27e-chi-pr.enterprise.ctl.io

2021-07-15 12:18 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-107/6/. :x:

2021-07-16 07:07 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-107/7/. :white_check_mark:

2021-07-16 07:07 UTC, SCMAUTO commented
You can check this PRs instance in https://3d0f9f63ecaf50f227fe9ef2ed41f261ecd3b252-chi-pr.enterprise.ctl.io

2021-07-16 15:13 UTC, janibolkvadze requested changes

2021-07-16 15:13 UTC, janibolkvadze commented on src/chi-vue/src/constants/types.ts
> +  disabledSelection?: boolean;
```suggestion
  selectionDisabled?: boolean;
```
Thoughts on calling it the other way around?

2021-07-16 15:56 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-107/8/. :x:

2021-07-16 16:17 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-107/9/. :white_check_mark:

2021-07-16 16:17 UTC, SCMAUTO commented
You can check this PRs instance in https://55e9531ace855b6b7864d6150f4ecc1bcfcefa70-chi-pr.enterprise.ctl.io

2021-07-19 11:37 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-107/10/. :x:

2021-07-19 13:48 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-107/11/. :white_check_mark:

2021-07-19 13:48 UTC, SCMAUTO commented
You can check this PRs instance in https://5ea6ec98204dd767d462818b7701a5971282da40-chi-pr.enterprise.ctl.io

2021-07-20 10:10 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-107/12/. :x:

2021-07-20 10:43 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-107/13/. :x:

2021-07-20 11:32 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-107/14/. :x:

2021-07-20 12:16 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-107/15/. :x:

2021-07-20 14:29 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-107/16/. :x:

2021-07-20 14:32 UTC, janibolkvadze approved these changes

2021-07-20 14:36 UTC, jllr approved these changes

2021-07-20 14:54 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-107/17/. :x:

2021-07-20 15:15 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-107/18/. :white_check_mark:

2021-07-20 15:15 UTC, SCMAUTO commented
You can check this PRs instance in https://7131ebaa05d3089bb5590d47d0093110aa1e38ab-chi-pr.enterprise.ctl.io

2021-07-20 15:16 UTC, merged