[FSDE-1174] Update the Chi-Vue boilerplate with new version of CHI-VUE
CenturyLink/Chi pull request #109
Opened 2021-07-15 13:13 UTC by aryaroudi

2021-07-15 13:38 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-109/1/. :x:

2021-07-15 14:07 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-109/2/. :white_check_mark:

2021-07-15 14:07 UTC, SCMAUTO commented
You can check this PRs instance in https://c8974305a2f8425d29cf6863c13025878acdd68d-chi-pr.enterprise.ctl.io

2021-07-16 15:44 UTC, janibolkvadze requested changes

2021-07-16 15:44 UTC, janibolkvadze commented on src/boilerplates/vue/chi-vue-boilerplate/vue.config.js
> +    },
```suggestion
```

2021-07-16 16:00 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-109/3/. :x:

2021-07-19 09:18 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-109/4/. :x:

2021-07-19 11:40 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-109/5/. :x:

2021-07-19 13:50 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-109/6/. :white_check_mark:

2021-07-19 13:51 UTC, SCMAUTO commented
You can check this PRs instance in https://82fb7c3f0129241e706ff2010548635fbeea5c75-chi-pr.enterprise.ctl.io

2021-07-20 08:03 UTC, janibolkvadze approved these changes

2021-07-20 09:26 UTC, jllr requested changes

2021-07-20 09:26 UTC, jllr commented on src/boilerplates/vue/chi-vue-boilerplate/package.json
> +    "@centurylink/chi-vue": "1.0.0",
```suggestion
    "@centurylink/chi-vue": "1.0.1",
```

2021-07-20 09:26 UTC, jllr commented on src/boilerplates/vue/chi-vue-boilerplate/src/components/Header.vue
>              </button>
@aryaroudi Tooltip is missing in notifications btn. Can you add it?

2021-07-20 09:26 UTC, jllr commented on src/boilerplates/vue/chi-vue-boilerplate/vue.config.js
> +    configureWebpack: config => {
@aryaroudi indentation looks a little off, please take a look.

2021-07-20 10:09 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-109/7/. :x:

2021-07-20 10:53 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-109/8/. :x:

2021-07-20 11:33 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-109/9/. :x:

2021-07-20 12:17 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-109/10/. :x:

2021-07-20 12:25 UTC, aryaroudi commented on src/boilerplates/vue/chi-vue-boilerplate/vue.config.js
> +    configureWebpack: config => {
hey @jllr I don't think so, looks good on my side 
![image](https://user-images.githubusercontent.com/43990136/126323366-82fc32f9-f694-441d-a034-e0bb435d456a.png)

2021-07-20 12:29 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-109/11/. :x:

2021-07-20 12:34 UTC, janibolkvadze approved these changes

2021-07-20 12:53 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-109/12/. :x:

2021-07-20 13:11 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-109/13/. :white_check_mark:

2021-07-20 13:11 UTC, SCMAUTO commented
You can check this PRs instance in https://12e7f6b6ec72244c1d2c6bbb32cc6994d0bffc4a-chi-pr.enterprise.ctl.io

2021-07-20 14:10 UTC, jllr approved these changes

2021-07-20 14:11 UTC, merged