[FSDE-1206] Add support for portal theme
CenturyLink/Chi pull request #114
Opened 2021-07-20 04:20 UTC by mattnickles

https://ctl.atlassian.net/browse/FSDE-1206

2021-07-20 04:37 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-114/1/. :x:

2021-07-20 10:10 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-114/2/. :x:

2021-07-20 19:11 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-114/5/. :white_check_mark:

2021-07-20 19:11 UTC, SCMAUTO commented
You can check this PRs instance in https://1e7ff8ccac19ab89e2e8be52271ad4920dee6110-chi-pr.enterprise.ctl.io

2021-07-21 01:52 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-114/6/. :white_check_mark:

2021-07-21 01:52 UTC, SCMAUTO commented
You can check this PRs instance in https://d6aa7d80d7429ea21536103898387d083493c062-chi-pr.enterprise.ctl.io

2021-07-21 15:09 UTC, janibolkvadze requested changes

2021-07-21 22:07 UTC, mattnickles commented on src/website/views/components/sidenav/_examples.pug
>  h3 Open on hover
Great catch! Thanks

2021-07-21 23:10 UTC, mattnickles commented on src/website/views/components/tooltip/_examples.pug
> +    | Use light tooltips for rendering tooltips on dark backgrounds. To use, apply the <code>data-tooltip-color="light"</code> attribute to the Tooltip trigger element.
I will move them. Thanks!

2021-07-22 02:08 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-114/7/. :white_check_mark:

2021-07-22 02:08 UTC, SCMAUTO commented
You can check this PRs instance in https://f2fffb3b3655c9aa0c9451d4356d928f819842e2-chi-pr.enterprise.ctl.io

2021-07-22 07:47 UTC, jllr approved these changes

2021-07-22 08:39 UTC, janibolkvadze approved these changes

2021-07-22 08:40 UTC, merged

2021-07-22 09:23 UTC, jllr commented
@mattnickles great job!!