[DPEDE-1683] Add prop to make column customization btn visible in too…
CenturyLink/Chi pull request #1153
Opened 2024-04-11 17:53 UTC by xft-dev

[https://ctl.atlassian.net/browse/DPEDE-1683](https://ctl.atlassian.net/browse/DPEDE-1683)

2024-04-12 10:15 UTC, ASanchLumen commented on src/chi-vue/src/components/data-table-toolbar/DataTableToolbar.vue
> +  columnsData?: DataTableColumnsData | {};
We can avoid creating two props and check if there is columns data. Also, columnsData cannot be `{}` as it requires the key `columns`:

```suggestion
  columnCustomizationData?: DataTableColumnsData;
```

```vue
        <ColumnCustomization v-if="columnCustomizationData" :columnsData="columnCustomizationData" />
```

2024-04-12 10:19 UTC, ASanchLumen requested changes
Code works great! Besides the code comment to simplify, don't forget visual & functional tests!

2024-04-12 14:11 UTC, xft-dev commented
[https://github.com/CenturyLink/Chi/pull/1153/commits/b3355c4949c83bd8ca12bc62e5f143b91a6bda63](https://github.com/CenturyLink/Chi/pull/1153/commits/b3355c4949c83bd8ca12bc62e5f143b91a6bda63)

Updated. 

Note: Typescript marks a type error in prop.

![image](https://github.com/CenturyLink/Chi/assets/156914938/b4b1df0a-eef2-490d-9d80-71e93c923f44)

2024-04-15 11:15 UTC, xft-dev commented
[https://github.com/CenturyLink/Chi/pull/1153/commits/948acb55a480e432a74b2a3ca488a0ec7fb7e930](https://github.com/CenturyLink/Chi/pull/1153/commits/948acb55a480e432a74b2a3ca488a0ec7fb7e930)

Tests added. Ready to review

2024-04-15 11:27 UTC, ASanchLumen commented
> [b3355c4](https://github.com/CenturyLink/Chi/commit/b3355c4949c83bd8ca12bc62e5f143b91a6bda63)
> 
> @ASanchLumen Updated. Thanks.
> 
> Note: Typescript marks a type error in prop.
> 
> ![image](https://private-user-images.githubusercontent.com/156914938/322011862-b4b1df0a-eef2-490d-9d80-71e93c923f44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxODA0MjgsIm5iZiI6MTcxMzE4MDEyOCwicGF0aCI6Ii8xNTY5MTQ5MzgvMzIyMDExODYyLWI0YjFkZjBhLWVlZjItNDkwZC05ZDgwLTcxZTkzYzkyM2Y0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxMTIyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTAzY2RhZTY3YmY3ZGFlZGRkZTAxNmE3MDFmZGMzZTJjZjkwZTM3OTgxZTI0OGU3ZTY2ODFiMTI2ODIyYTBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lcTjKQCR_BRtsIkTRUUTUUXKKQ20IPyu_oRVKO3xY0k)

The error is caused because the fixtures have no types, it can be avoided by explicitly saying that it's the correct type:

![image](https://github.com/CenturyLink/Chi/assets/148064753/219f5d1a-d48a-48e7-a405-652f2b2ff102)

2024-04-15 11:37 UTC, ASanchLumen approved these changes

2024-04-18 08:43 UTC, closed without merging