[DPEDE-1546] Create transfer list e2e tests
CenturyLink/Chi pull request #1259
Opened 2024-06-07 16:30 UTC by emerson-pereira

2024-06-12 12:18 UTC, xft-dev commented
I checked this PR and Modal tests are failing because some trigger buttons are missed.

![image](https://github.com/CenturyLink/Chi/assets/156914938/7711e26b-149d-458f-9850-6d29c0ba6758)

2024-06-17 15:34 UTC, xft-dev approved these changes
Nice job! The tests pass, I just had to run "npm run build:umd" before, in order to see the modal buttons.

2024-06-18 07:45 UTC, josecarlosgonzalezv requested changes
Good work. I would include tests for the wildcard and locked properties. 

Also test the different movements between columns and in the right column:

* items to left
* items to right
* items up
* items down
* all items to left
* all  items to right

2024-06-18 07:45 UTC, josecarlosgonzalezv commented on cypress/e2e/chi-vue/transfer-list.cy.js
> +    it(`should have class ${TRANSFER_LIST_CLASSES.TRANSFER_LIST_ELEMENT}`, () => {
Uppercase, check in every test

```suggestion
    it(`Should have class ${TRANSFER_LIST_CLASSES.TRANSFER_LIST_ELEMENT}`, () => {
```

2024-06-24 09:35 UTC, josecarlosgonzalezv approved these changes

2024-06-24 11:03 UTC, jllr approved these changes

2024-06-24 11:05 UTC, merged