[DPEDE-1977] Added helper message and state to search-input component
CenturyLink/Chi pull request #1264
Opened 2024-06-11 06:46 UTC by wojciechwlodarczyklumen

2024-06-11 08:57 UTC, josecarlosgonzalezv requested changes

2024-06-11 08:57 UTC, josecarlosgonzalezv commented on src/documentation/pages/components-wip/forms/search-input/_properties.vue
> +            tr
Don't need to add anything here as this is for the Vue component not for the web component which is automatically updated.

2024-06-12 13:34 UTC, josecarlosgonzalezv approved these changes

2024-06-13 07:08 UTC, xft-dev reviewed
Good work, I just see a couple of things regarding code snippet section:

- These props has not been added to SearchInput Vue component but I can see them in the Vue code snippet of the /documentation and /website. (See image)
- Indentation code in the code snippet section of /documentation (See image)

![image](https://github.com/CenturyLink/Chi/assets/156914938/3086ca38-2254-48d5-a148-f8bacbd57362)

2024-06-13 13:06 UTC, xft-dev approved these changes

2024-06-14 07:00 UTC, jllr approved these changes

2024-06-14 07:00 UTC, merged