[FSDE-1419] Add help icon support in App layout WC
CenturyLink/Chi pull request #131
Opened 2021-08-03 12:36 UTC by jllr

https://ctl.atlassian.net/browse/FSDE-1419

2021-08-03 13:10 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-131/1/. :white_check_mark:

2021-08-03 13:10 UTC, SCMAUTO commented
You can check this PRs instance in https://ff9220c3110fb059a0254c0d4d6658babc285a9b-chi-pr.enterprise.ctl.io

2021-08-03 13:34 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-131/2/. :white_check_mark:

2021-08-03 13:34 UTC, SCMAUTO commented
You can check this PRs instance in https://ff9220c3110fb059a0254c0d4d6658babc285a9b-chi-pr.enterprise.ctl.io

2021-08-03 15:53 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-131/3/. :white_check_mark:

2021-08-03 15:53 UTC, SCMAUTO commented
You can check this PRs instance in https://fec8d5a8c90f099519b504b8afc2a424e2a53c50-chi-pr.enterprise.ctl.io

2021-08-03 17:11 UTC, mattnickles approved these changes

2021-08-04 08:37 UTC, janibolkvadze requested changes

2021-08-04 08:37 UTC, janibolkvadze commented on src/website/views/templates/app-layout.pug
> +        | Use the <code>title=""</code> attribute to display a title above the application layout.
Do we need to repeat this?

2021-08-04 08:37 UTC, janibolkvadze commented on src/website/views/templates/app-layout.pug
> +                  <chi-button id="example__help-button" type="icon" size="sm" variant="flat" alternative-text="Help" slot="help-icon">
Do we need to use web components in HTML blueprint tab?

2021-08-04 08:37 UTC, janibolkvadze commented on src/website/views/templates/app-layout.pug
> +        | Use the <code>title=""</code> attribute to display a title above the application layout.
Same here

2021-08-04 08:37 UTC, janibolkvadze commented on src/website/views/templates/app-layout.pug
> +                  <chi-button id="example__help-button" type="icon" size="sm" variant="flat" alternative-text="Help" slot="help-icon" class="-ml--1">
Same here

2021-08-04 08:37 UTC, janibolkvadze commented on src/website/views/templates/app-layout.pug
> +                  <chi-button id="example__help-button" type="icon" size="sm" variant="flat" alternative-text="Help" slot="help-icon" class="-ml--1">
Same here

2021-08-04 12:03 UTC, SCMAUTO commented
You can check this PRs instance in https://727d5aacd1f202b099dff69aa2daf3d0061b7a40-chi-pr.enterprise.ctl.io

2021-08-04 13:09 UTC, janibolkvadze approved these changes

2021-08-04 13:09 UTC, merged