[DPEDE-2163] update change button to edit in expansion panel
CenturyLink/Chi pull request #1331
Opened 2024-07-17 16:01 UTC by emerson-pereira

https://ctl.atlassian.net/browse/DPEDE-2163

2024-07-18 06:11 UTC, wojciechwlodarczyklumen approved these changes
Looks okay !

2024-07-18 09:00 UTC, wojciechwlodarczyklumen approved these changes

2024-07-18 09:05 UTC, josecarlosgonzalezv requested changes
Please review that you only change **names** not panel actions, slots or whatever

2024-07-18 09:05 UTC, josecarlosgonzalezv commented on test/chi/chi-vue/expansion-panel.pug
> +      chi-button(color='primary' variant='flat' @click="active = 0" data-chi-epanel-action='edit')
```suggestion
      chi-button(color='primary' variant='flat' @click="active = 0" data-chi-epanel-action='change')
```

2024-07-18 14:17 UTC, emerson-pereira commented on test/chi/chi-vue/expansion-panel.pug
> +      chi-button(color='primary' variant='flat' @click="active = 0" data-chi-epanel-action='edit')
Done

2024-07-19 07:38 UTC, josecarlosgonzalezv approved these changes

2024-07-19 07:42 UTC, jllr approved these changes

2024-07-19 07:42 UTC, merged