[FSDE-1249] Fix Internal footer links in the HTML Blueprint code
CenturyLink/Chi pull request #136
Opened 2021-08-04 13:58 UTC by josecarlosgonzalezv

- [x] Changed some URLs that were bad.

2021-08-04 14:19 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-136/1/. :white_check_mark:

2021-08-04 14:19 UTC, SCMAUTO commented
You can check this PRs instance in https://e8719435fc00bfb2eed5f5af3417968c7150104f-chi-pr.enterprise.ctl.io

2021-08-04 15:02 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-136/2/. :x:

2021-08-04 15:25 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-136/3/. :white_check_mark:

2021-08-04 15:25 UTC, SCMAUTO commented
You can check this PRs instance in https://dbbe805b5dec45e5ba45083c7726113e28d8d875-chi-pr.enterprise.ctl.io

2021-08-04 17:38 UTC, janibolkvadze requested changes

2021-08-04 17:38 UTC, janibolkvadze commented on src/website/views/components/footer/_examples.pug
> +                        >
I this proper indentation / linting?

2021-08-04 18:04 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-136/4/. :x:

2021-08-04 18:29 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-136/5/. :x:

2021-08-04 19:37 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-136/6/. :white_check_mark:

2021-08-04 19:37 UTC, SCMAUTO commented
You can check this PRs instance in https://e7debeb5063306a9f1f681e8cbc38756c230c7b6-chi-pr.enterprise.ctl.io

2021-08-05 07:48 UTC, josecarlosgonzalezv commented on src/website/views/components/footer/_examples.pug
> +                        >
Solved with 2 spaces.

2021-08-05 07:59 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-136/7/. :white_check_mark:

2021-08-05 07:59 UTC, SCMAUTO commented
You can check this PRs instance in https://dba8229312fdf5400f25062641db45441d51cc66-chi-pr.enterprise.ctl.io

2021-08-05 08:29 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-136/8/. :white_check_mark:

2021-08-05 08:29 UTC, SCMAUTO commented
You can check this PRs instance in https://8baf27fc4c9f0c97fbb8b0368b2def049ef95f97-chi-pr.enterprise.ctl.io

2021-08-05 08:35 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-136/9/. :x:

2021-08-05 08:51 UTC, jllr approved these changes

2021-08-05 08:55 UTC, janibolkvadze approved these changes

2021-08-05 09:08 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-136/10/. :white_check_mark:

2021-08-05 09:08 UTC, SCMAUTO commented
You can check this PRs instance in https://35e902a305e6fc0428a1fd90b0173b4cc63f4fc5-chi-pr.enterprise.ctl.io

2021-08-05 09:22 UTC, merged