[FSDE-8075] Migrate Flag Icon component to vue documentation
CenturyLink/Chi pull request #211
Opened 2021-10-25 16:26 UTC by soujanreddy

2021-11-02 10:39 UTC, evansito approved these changes

2021-11-02 10:40 UTC, evansito approved these changes

2021-11-02 20:04 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-211/14/. :white_check_mark:

2021-11-02 20:04 UTC, SCMAUTO commented
You can check this PRs instance in https://78d54ffd0223be244edf249a13d59eb229fe8d2e-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-211-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-02 22:33 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-211/15/. :white_check_mark:

2021-11-02 22:33 UTC, SCMAUTO commented
You can check this PRs instance in https://b9512a8c9827525894ed9d5cd63f5e211ab55114-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-211-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-03 12:50 UTC, josecarlosgonzalezv requested changes

2021-11-03 12:50 UTC, josecarlosgonzalezv commented on src/documentation/pages/components/flag-icon/examples/_area.vue
> +  <ComponentExample title="Country/Region" id="area_lumen_centurylink" :tabs="exampleTabs">
```suggestion
  <ComponentExample title="Country/Region" id="country_region" :tabs="exampleTabs">
```

2021-11-03 12:50 UTC, josecarlosgonzalezv commented on src/documentation/pages/components/flag-icon/examples/_area.vue
> +export default class SolidExample extends Vue {
```suggestion
export default class CountryRegion extends Vue {
```

2021-11-03 12:50 UTC, josecarlosgonzalezv commented on src/documentation/pages/components/flag-icon/examples/_sizes.vue
> +  <ComponentExample title="Sizes" id="sizes_lumen_centurylink" :tabs="exampleTabs">
```suggestion
  <ComponentExample title="Sizes" id="sizes" :tabs="exampleTabs">
```

2021-11-03 12:50 UTC, josecarlosgonzalezv commented on src/documentation/pages/components/flag-icon/examples/_sizes.vue
> +export default class SizesExample extends Vue {
```suggestion
export default class Sizes extends Vue {
```

2021-11-03 12:50 UTC, josecarlosgonzalezv commented on src/documentation/pages/components/flag-icon/examples/index.vue
> +      <Area />
```suggestion
      <CountryRegion />
```

2021-11-03 12:50 UTC, josecarlosgonzalezv commented on src/documentation/pages/components/flag-icon/examples/index.vue
> +import Area from './_area.vue';
```suggestion
import CountryRegion from './_country_region.vue';
```

2021-11-03 12:50 UTC, josecarlosgonzalezv commented on src/documentation/pages/components/flag-icon/examples/index.vue
> +    Area,
```suggestion
    CountryRegion,
```

2021-11-03 12:50 UTC, josecarlosgonzalezv commented on src/documentation/pages/components/flag-icon/examples/index.vue
> +export default class FlagIconExamples extends Vue {}
```suggestion
export default class Examples extends Vue {}
```

2021-11-03 12:50 UTC, josecarlosgonzalezv commented on src/documentation/pages/components/flag-icon/examples/_area.vue
> +<template lang="pug">
Change filename to **`_country_region.vue`**

2021-11-03 15:08 UTC, josecarlosgonzalezv approved these changes

2021-11-03 15:22 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-211/16/. :white_check_mark:

2021-11-03 15:22 UTC, SCMAUTO commented
You can check this PRs instance in https://f3e8358fd1cf6d76785e308d8d468aef21aeb65c-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-211-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-03 16:29 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-211/17/. :white_check_mark:

2021-11-03 16:29 UTC, SCMAUTO commented
You can check this PRs instance in https://b04e9574bd01acb834176ce14eed700e676acbc3-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-211-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-03 17:40 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-211/18/. :white_check_mark:

2021-11-03 17:40 UTC, SCMAUTO commented
You can check this PRs instance in https://f1b7d6970a70cf5b4bcc0697e464024ed72d72c4-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-211-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-03 18:30 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-211/19/. :white_check_mark:

2021-11-03 18:30 UTC, SCMAUTO commented
You can check this PRs instance in https://d3641d11490297282e8ef80ebd051304e8a30d38-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-211-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-03 19:45 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-211/20/. :white_check_mark:

2021-11-03 19:45 UTC, SCMAUTO commented
You can check this PRs instance in https://2a768d4669ed69c9636506be6ba27584cf5efea6-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-211-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-04 11:02 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-211/21/. :white_check_mark:

2021-11-04 11:02 UTC, SCMAUTO commented
You can check this PRs instance in https://e5794e310dbbc5cf70183e1f376210efed0a78df-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-211-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-04 13:34 UTC, jllr approved these changes

2021-11-04 13:38 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-211/22/. :x:

2021-11-04 13:50 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-211/23/. :x:

2021-11-04 14:04 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-211/24/. :x:

2021-11-04 14:49 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-211/25/. :white_check_mark:

2021-11-04 14:49 UTC, SCMAUTO commented
You can check this PRs instance in https://53436193e3a8c6757982643e98ad4bd68f80ff8c-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-211-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-04 14:55 UTC, janibolkvadze approved these changes

2021-11-04 15:02 UTC, merged