[FSDE-8427] Migrate file input component to vue documentation
CenturyLink/Chi pull request #213
Opened 2021-10-26 20:11 UTC by soujanreddy

2021-11-02 10:41 UTC, evansito approved these changes

2021-11-02 20:09 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-213/12/. :white_check_mark:

2021-11-02 20:09 UTC, SCMAUTO commented
You can check this PRs instance in https://98eab561c9b54772c0d40ff04d0975b9ffc841df-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-213-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-02 22:39 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-213/13/. :white_check_mark:

2021-11-02 22:39 UTC, SCMAUTO commented
You can check this PRs instance in https://bca09cb8301f9e1cf08db1cdd3d01e980a126268-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-213-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-03 12:39 UTC, josecarlosgonzalezv commented on src/documentation/pages/components/file-input/examples/_base.vue
> +  <ComponentExample title="Base" id="base_lumen_centurylink" :tabs="exampleTabs">
```suggestion
  <ComponentExample title="Base" id="base" :tabs="exampleTabs">
```

2021-11-03 12:40 UTC, josecarlosgonzalezv commented on src/documentation/pages/components/file-input/examples/_base.vue
> +declare const chi: any;
```suggestion
```

2021-11-03 12:40 UTC, josecarlosgonzalezv commented on src/documentation/pages/components/file-input/examples/_disabled.vue
> +<ComponentExample title="Disabled" id="disabled_lumen_centurylink" :tabs="exampleTabs">
```suggestion
<ComponentExample title="Disabled" id="disabled" :tabs="exampleTabs">
```

2021-11-03 12:40 UTC, josecarlosgonzalezv commented on src/documentation/pages/components/file-input/examples/_disabled.vue
> +declare const chi: any;
```suggestion
```

2021-11-03 12:41 UTC, josecarlosgonzalezv commented on src/documentation/pages/components/file-input/examples/_disabled.vue
> +export default class DisabledExample extends Vue {
```suggestion
export default class Disabled extends Vue {
```

2021-11-03 12:41 UTC, josecarlosgonzalezv commented on src/documentation/pages/components/file-input/examples/_base.vue
> +export default class BaseExample extends Vue {
```suggestion
export default class Base extends Vue {
```

2021-11-03 12:41 UTC, josecarlosgonzalezv commented on src/documentation/pages/components/file-input/examples/_sizes.vue
> +  <ComponentExample title="Sizes" id="sizes_lumen_centurylink" :tabs="exampleTabs">
```suggestion
  <ComponentExample title="Sizes" id="sizes" :tabs="exampleTabs">
```

2021-11-03 12:42 UTC, josecarlosgonzalezv commented on src/documentation/pages/components/file-input/examples/_sizes.vue
> +declare const chi: any;
```suggestion
```

2021-11-03 12:42 UTC, josecarlosgonzalezv commented on src/documentation/pages/components/file-input/examples/_sizes.vue
> +export default class SizesExample extends Vue {
```suggestion
export default class Sizes extends Vue {
```

2021-11-03 12:42 UTC, josecarlosgonzalezv commented on src/documentation/pages/components/file-input/examples/index.vue
> +export default class FileInputExamples extends Vue {}
```suggestion
export default class Examples extends Vue {}
```

2021-11-03 15:07 UTC, josecarlosgonzalezv approved these changes

2021-11-03 15:25 UTC, SCMAUTO commented
You can check this PRs instance in https://af379fd31314a0d9b4e133031e8a449dac2f0101-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-213-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-03 16:35 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-213/15/. :white_check_mark:

2021-11-03 16:35 UTC, SCMAUTO commented
You can check this PRs instance in https://1a52718977788aedf2f8daa9912dd7282d9541c0-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-213-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-03 17:41 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-213/16/. :white_check_mark:

2021-11-03 17:41 UTC, SCMAUTO commented
You can check this PRs instance in https://a333126e6580ad99ed5dd8b4726e725ccf8201ae-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-213-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-03 18:33 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-213/17/. :white_check_mark:

2021-11-03 18:33 UTC, SCMAUTO commented
You can check this PRs instance in https://d10431ae46afc5d5b0cb24aa853d4242ec0ff541-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-213-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-03 19:52 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-213/18/. :white_check_mark:

2021-11-03 19:52 UTC, SCMAUTO commented
You can check this PRs instance in https://605b34b97b86b8b0f2d012758f9a453eb5e7faa3-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-213-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-04 10:55 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-213/19/. :white_check_mark:

2021-11-04 10:55 UTC, SCMAUTO commented
You can check this PRs instance in https://debdce4520d114318949d97638ea5613d6b344a9-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-213-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-04 16:20 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-213/21/. :white_check_mark:

2021-11-04 16:20 UTC, SCMAUTO commented
You can check this PRs instance in https://13d4a0363cbfd176063997d29eada49c7fd4c57a-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-213-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-04 18:33 UTC, soujanreddy commented
@jllr Made updates to the portal theme as per your comment. Please review.

2021-11-04 18:49 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-213/22/. :white_check_mark:

2021-11-04 18:49 UTC, SCMAUTO commented
You can check this PRs instance in https://70dce0712b2f016a03ca9953232cf7b99939dcbc-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-213-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-04 19:13 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-213/23/. :white_check_mark:

2021-11-04 19:13 UTC, SCMAUTO commented
You can check this PRs instance in https://d0c76ba90c6c83799da19a9ce02784595c0ff2dc-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-213-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-05 10:26 UTC, jllr requested changes

2021-11-05 10:29 UTC, jllr approved these changes

2021-11-05 10:32 UTC, janibolkvadze approved these changes

2021-11-05 10:34 UTC, merged