[FSDE-9221] Create backstop visual regresion test of data table
CenturyLink/Chi pull request #242
Opened 2021-11-24 11:32 UTC by josecarlosgonzalezv

2021-11-24 12:07 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/1/. :white_check_mark:

2021-11-24 12:07 UTC, SCMAUTO commented
You can check this PRs instance in https://07393ef93a431a46ecec428e89e8fe2f70debe3c-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-242-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-24 14:09 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/2/. :white_check_mark:

2021-11-24 14:09 UTC, SCMAUTO commented
You can check this PRs instance in https://fc07c1f69c94deabc0e9c820a738de00a40dcb88-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-242-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-24 15:15 UTC, evansito commented on backstop-non-responsive.json
> +}
Newline at the end of file is missing

2021-11-24 15:15 UTC, evansito commented on test/chi/components/data-table.pug
> +              input#jumper-input-17.chi-input(type='text')
Same here

2021-11-24 21:00 UTC, soujanreddy approved these changes

2021-11-25 09:25 UTC, evansito approved these changes

2021-11-25 10:06 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/3/. :white_check_mark:

2021-11-25 10:06 UTC, SCMAUTO commented
You can check this PRs instance in https://af3f000658dff0aaf7887ee9ee83100217a9370a-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-242-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-25 16:18 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/4/. :white_check_mark:

2021-11-25 16:18 UTC, SCMAUTO commented
You can check this PRs instance in https://419903d86dfdb98289c2b0dfbe88e7fabb1f21e9-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-242-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-25 18:18 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/5/. :white_check_mark:

2021-11-25 18:18 UTC, SCMAUTO commented
You can check this PRs instance in https://e1ee0bfd3f673576e3ecf50f7f8b8883d07f3d81-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-242-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-26 10:14 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/6/. :white_check_mark:

2021-11-26 10:15 UTC, SCMAUTO commented
You can check this PRs instance in https://ab66cafad6918eceedb016d0c64f639235f06729-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-242-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-11-29 11:49 UTC, janibolkvadze requested changes

2021-11-29 11:49 UTC, janibolkvadze commented on test/chi/components/data-table.pug
> +---
Can we break this down into separate files, like
_base.pug
_accordion.pug
_child.pug
etc

and import them into data-table/index.pug like:
include ./_base
include ./_accordion
include ./_accordion
?

2021-11-29 11:49 UTC, janibolkvadze commented on test/chi/components/data-table.pug
> +.test-base
```suggestion
.test-base.-w--100
```
Please, provide the class to all the test cases as currently, they render with a narrow width.

2021-11-29 11:49 UTC, janibolkvadze commented on test/chi/components/data-table.pug
> +      div No matches found. Please revise search criteria and try again.
```suggestion
        | No matches found. Please revise search criteria and try again.
```
Please test if this renders correctly as currently, the text appears outside the row.

2021-11-29 11:49 UTC, janibolkvadze commented on test/chi/components/data-table.pug
> +.test-hover
This test case does not provide additional value as the rendered image does not show the hover state of the rows

2021-11-29 11:49 UTC, janibolkvadze commented on test/chi/components/data-table.pug
> +.test-hover
Let's remove it.

2021-11-29 11:49 UTC, janibolkvadze commented on test/chi/components/data-table.pug
> +            input#checkbox-ba1.chi-checkbox__input(type='checkbox')
```suggestion
            input#checkbox-ba1.chi-checkbox__input(type='checkbox' checked)
```

2021-11-29 11:49 UTC, janibolkvadze commented on test/chi/components/data-table.pug
> +              input#radio-ba2.chi-radio__input(type='radio' name='radios')
```suggestion
              input#radio-ba2.chi-radio__input(type='radio' name='radios' checked)
```

2021-11-29 11:49 UTC, janibolkvadze commented on test/chi/components/data-table.pug
> +.test-accordion-portal
Portal test cases will be set up in a different way. Let's keep the file Lumen theme specific

2021-11-29 11:49 UTC, janibolkvadze commented on test/chi/components/data-table.pug
> +                  i.chi-icon.icon-minus(aria-hidden='true')
This Expansion icon is from the Portal theme.
This and several following examples use portal markup. Please, keep the test page Lumen theme-specific.

2021-11-29 12:13 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/7/. :white_check_mark:

2021-11-29 12:13 UTC, SCMAUTO commented
You can check this PRs instance in https://39a502fbbe3e588d61e7c609fcb1c6421e4cd052-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-242-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-01 17:43 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/8/. :white_check_mark:

2021-12-01 17:43 UTC, SCMAUTO commented
You can check this PRs instance in https://14de76ea4e888af1b74d982590b96278da67271c-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-242-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-02 11:08 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/9/. :x:

2021-12-02 15:45 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/10/. :white_check_mark:

2021-12-02 15:45 UTC, SCMAUTO commented
You can check this PRs instance in https://9d91169de731b0cbffa4f82c33ebf536c4057a03-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-242-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-07 09:21 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/11/. :white_check_mark:

2021-12-07 09:21 UTC, SCMAUTO commented
You can check this PRs instance in https://e0a377e8d260d375082108033db139a7ddc36eae-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-242-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-07 09:58 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/12/. :white_check_mark:

2021-12-07 09:58 UTC, SCMAUTO commented
You can check this PRs instance in https://e711c68a7620e1e51fc6861aec7861fc44c64ecc-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-242-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-07 10:49 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/13/. :x:

2021-12-07 13:14 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/14/. :white_check_mark:

2021-12-07 13:14 UTC, SCMAUTO commented
You can check this PRs instance in https://4655c8e60bc54f8187b81b003d2ac7f0d5a971be-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-242-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-09 18:30 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/15/. :x:

2021-12-10 13:25 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/16/. :white_check_mark:

2021-12-10 13:25 UTC, SCMAUTO commented
You can check this PRs instance in https://6bb190ff97f98df9184ce38f035958e2f67d09fc-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-242-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-13 10:52 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/17/. :white_check_mark:

2021-12-13 10:52 UTC, SCMAUTO commented
You can check this PRs instance in https://2fcf6a2eb2edcb07f6e3fa5669a518417affb7bf-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-242-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-13 14:55 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/19/. :white_check_mark:

2021-12-13 14:55 UTC, SCMAUTO commented
You can check this PRs instance in https://30400e68199e7587df458e8e6ce5e1453ff068f8-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-242-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-14 15:44 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/20/. :x:

2021-12-14 16:07 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/21/. :x:

2021-12-14 16:55 UTC, evansito approved these changes

2021-12-15 11:31 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/22/. :x:

2021-12-15 12:13 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/23/. :white_check_mark:

2021-12-15 12:13 UTC, SCMAUTO commented
You can check this PRs instance in https://c033e6363d7a3e3015481c7f1919297aa14c3906-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-242-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-15 14:52 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/24/. :x:

2021-12-15 19:43 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/25/. :x:

2021-12-15 22:39 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/26/. :white_check_mark:

2021-12-15 22:39 UTC, SCMAUTO commented
You can check this PRs instance in https://fef8ca7f622fd1781ff94d1568450000122943bf-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-242-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-17 18:31 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/28/. :white_check_mark:

2021-12-17 18:31 UTC, SCMAUTO commented
You can check this PRs instance in https://7b36c321d037cf177a5cf82d740bd9c1274912e6-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-242-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-20 14:25 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/29/. :white_check_mark:

2021-12-20 14:25 UTC, SCMAUTO commented
You can check this PRs instance in https://d7287caabccce9791bde82be80d626af60cfcd02-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-242-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-21 07:22 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/30/. :white_check_mark:

2021-12-21 07:22 UTC, SCMAUTO commented
You can check this PRs instance in https://fc619f82778500db83f61b4df10728e65e4127c3-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-242-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-22 13:18 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/33/. :x:

2022-01-07 14:33 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/40/. :x:

2022-01-10 10:39 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/42/. :x:

2022-01-10 15:22 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/44/. :white_check_mark:

2022-01-10 15:22 UTC, SCMAUTO commented
You can check this PRs instance in https://d37ff24762ac56d5331b7532d2cf605bcb4c0246-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-242-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-14 11:02 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/47/. :x:

2022-01-14 17:18 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/49/. :x:

2022-01-17 11:44 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/50/. :x:

2022-01-17 13:18 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-242/51/. :x:

2022-08-19 10:28 UTC, closed without merging