[FSDE-10859] Fix checkbox issue for multiple lines
CenturyLink/Chi pull request #248
Opened 2021-11-30 04:03 UTC by soujanreddy

2021-11-30 04:24 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-248/1/. :x:

2021-12-01 17:35 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-248/2/. :x:

2021-12-01 18:18 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-248/3/. :x:

2021-12-01 19:50 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-248/4/. :white_check_mark:

2021-12-01 19:50 UTC, SCMAUTO commented
You can check this PRs instance in https://81e4f27053df225791c6e248d8a5289e47bd65bf-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-248-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-02 11:19 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-248/5/. :white_check_mark:

2021-12-02 11:19 UTC, SCMAUTO commented
You can check this PRs instance in https://7e8efa9ea9b472706b74484cc888bdd621b1d28f-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-248-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-02 15:39 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-248/6/. :x:

2021-12-02 16:08 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-248/7/. :x:

2021-12-02 16:32 UTC, mattnickles approved these changes

2021-12-03 16:42 UTC, evansito approved these changes

2021-12-03 16:51 UTC, jllr requested changes

2021-12-03 16:51 UTC, jllr commented on src/chi/components/checkbox/checkbox.scss
> +        top: 0.1rem;
Please revert to the previous line and value

2021-12-03 16:51 UTC, jllr commented on src/chi/components/checkbox/checkbox.scss
> +        top: 0.3rem;
Please revert to the previous line and set value to 0.3125rem

2021-12-03 20:34 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-248/8/. :white_check_mark:

2021-12-03 20:34 UTC, SCMAUTO commented
You can check this PRs instance in https://bb1ec1031c96154b443af6ea8318c4bf11609293-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-248-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-07 09:10 UTC, janibolkvadze approved these changes

2021-12-07 09:40 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-248/9/. :white_check_mark:

2021-12-07 09:40 UTC, SCMAUTO commented
You can check this PRs instance in https://b6f38959b4e5ca2e0b80e4ce97908922fe1c83a9-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-248-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-07 10:09 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-248/10/. :white_check_mark:

2021-12-07 10:09 UTC, SCMAUTO commented
You can check this PRs instance in https://eac602084b26c6cf09ce516bc1798bc2bce60a95-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-248-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-07 10:11 UTC, jllr approved these changes

2021-12-07 10:28 UTC, merged