[FSDE-11702] Migrate Modal component documentation
CenturyLink/Chi pull request #267
Opened 2021-12-19 23:19 UTC by soujanreddy

2021-12-20 00:03 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/1/. :white_check_mark:

2021-12-20 00:03 UTC, SCMAUTO commented
You can check this PRs instance in https://4c28f087ff73f1c82e65c01c0a0176ac2d1e931d-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-267-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-20 00:25 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/2/. :white_check_mark:

2021-12-20 00:25 UTC, SCMAUTO commented
You can check this PRs instance in https://4c28f087ff73f1c82e65c01c0a0176ac2d1e931d-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-267-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-20 19:21 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/3/. :white_check_mark:

2021-12-20 19:21 UTC, SCMAUTO commented
You can check this PRs instance in https://c207649e821e94e2ae2266b34dacac90e7649508-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-267-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-20 19:57 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/4/. :white_check_mark:

2021-12-20 19:58 UTC, SCMAUTO commented
You can check this PRs instance in https://5251e36379c6842e6a78ac0e89ee7ee854b9ef5d-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-267-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-21 09:05 UTC, evansito commented on src/documentation/pages/components/modal/examples/_base.vue
> +    const openModalPopup = document.getElementById('modal-trigger-1');
I'd suggest either using it directly
chi.modal(document.getElementById('modal-trigger-1'));

or if using the const, adding a newline:
    const openModalPopup = document.getElementById('modal-trigger-1');

    chi.modal(document.getElementById('modal-trigger-1'));

2021-12-21 09:06 UTC, evansito commented on src/documentation/pages/components/modal/examples/_center.vue
> +declare const chi: any;
we can remove this if it's not used

2021-12-21 09:06 UTC, evansito commented on src/documentation/pages/components/modal/examples/_inverse.vue
> +declare const chi: any;
same here and so on

2021-12-21 09:07 UTC, evansito commented on src/documentation/pages/components/modal/examples/_multi_step.vue
> +<ComponentExample title="Multi-step" id="multi_step" padding="-p--0" :tabs="exampleTabs">
i'd recommend naming ids using dash - like e.g. multi-step as per convention iirc 🤔

2021-12-21 09:09 UTC, evansito commented on src/documentation/pages/components/modal/index.vue
> +  <Wrapper>
Apparently adding <Wrapper> to the root-most index.vue breaks navigation :( so we should exceptionally use <div> here instead

2021-12-21 09:13 UTC, evansito requested changes

2021-12-21 09:13 UTC, evansito commented on src/documentation/pages/components/modal/_accessibility.vue
> +  export default class Accessibility extends Vue {
formatting seems a bit off here, could we reformat this just in case?

2021-12-21 16:43 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/7/. :white_check_mark:

2021-12-21 16:43 UTC, SCMAUTO commented
You can check this PRs instance in https://8a3a1026290cef6ab66d176607d4baa41d4c0031-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-267-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-21 18:18 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/9/. :white_check_mark:

2021-12-21 18:18 UTC, SCMAUTO commented
You can check this PRs instance in https://f55b74206b0f3eb4e32a1ab78c3f433d12ed3043-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-267-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-30 10:04 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/10/. :white_check_mark:

2021-12-30 10:04 UTC, SCMAUTO commented
You can check this PRs instance in https://e47ab3c736a1bcd6c55c4af173f270d339b83379-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-267-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-03 19:33 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/11/. :white_check_mark:

2022-01-03 19:33 UTC, SCMAUTO commented
You can check this PRs instance in https://ed45766326626d1cf734f1d2ed5c700370f27d81-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-267-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-10 17:50 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/13/. :white_check_mark:

2022-01-10 17:50 UTC, SCMAUTO commented
You can check this PRs instance in https://ee341518eb4041f3a362c312df596e31047976f0-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-267-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-10 18:39 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/14/. :white_check_mark:

2022-01-10 18:39 UTC, SCMAUTO commented
You can check this PRs instance in https://d19d14ee98a765b0b1631ee5cf6bdb2705a22e3c-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-267-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-12 14:35 UTC, evansito commented on src/documentation/pages/components/modal/examples/_base.vue
> +    const openModalPopup = document.getElementById('modal-trigger-1');
this remains unfixed

2022-01-12 14:37 UTC, evansito approved these changes

2022-01-12 17:33 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/16/. :white_check_mark:

2022-01-12 17:33 UTC, SCMAUTO commented
You can check this PRs instance in https://f57112fd3be2ab9e5e60c273bede8c673dfab008-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-267-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-13 16:12 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/18/. :white_check_mark:

2022-01-13 21:26 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/19/. :white_check_mark:

2022-01-13 21:26 UTC, SCMAUTO commented
You can check this PRs instance in https://3775411505c3a7e64c58bf0a92f6921094bf7a24-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-267-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-14 11:22 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/20/. :white_check_mark:

2022-01-14 11:22 UTC, SCMAUTO commented
You can check this PRs instance in https://61e84e340a186b4f27e74bde1957b5c1c8143ce9-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-267-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-14 17:30 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/22/. :white_check_mark:

2022-01-14 17:30 UTC, SCMAUTO commented
You can check this PRs instance in https://a66e4f5c8da802f6d031e57082380cb247e6a5c9-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-267-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-17 10:14 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/23/. :x:

2022-01-17 13:43 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/25/. :white_check_mark:

2022-01-17 13:43 UTC, SCMAUTO commented
You can check this PRs instance in https://dfb5da995febf2d575785dbc0e3b6d51ed3dbdd1-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-267-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-18 21:45 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/28/. :x:

2022-01-26 15:21 UTC, evansito requested changes

2022-01-26 15:21 UTC, evansito commented on src/documentation/pages/components/modal/_accessibility.vue
> +      .chi-card__content
AccessibilityComingSoon component

2022-01-26 15:21 UTC, evansito commented on src/documentation/pages/components/modal/examples/_alert.vue
> +          active: true,
no need to use active: true here since the above one is disabled hence this tab will resort to active by default

2022-01-26 15:21 UTC, evansito commented on src/documentation/pages/components/modal/examples/_base.vue
> +    .-p--3(slot="example")
same issue with paddings here, please use the default -p--3

2022-01-26 15:21 UTC, evansito commented on src/documentation/pages/components/modal/examples/_base.vue
> +          active: true,
same here and in the other examples

2022-01-26 15:21 UTC, evansito commented on src/documentation/pages/components/modal/examples/_base.vue
> +    chi.modal(document.getElementById('modal-trigger-1'));
refs should be used instead of ids

2022-01-26 15:21 UTC, evansito commented on src/documentation/pages/components/modal/examples/_scrollable_long.vue
> +export default class ScrollLong extends Vue {}
i should naming it more in agreement with the id and title, same with the file name. E.g. ScrollingLongContent

2022-01-26 15:21 UTC, evansito commented on src/documentation/pages/components/modal/examples/_scrollable_requirements.vue
> +export default class ScrollReq extends Vue {}
same suggestion here

2022-01-26 15:21 UTC, evansito commented on src/documentation/pages/components/modal/examples/_subtitle.vue
> +export default class SubTitle extends Vue {}
same here

2022-01-26 15:21 UTC, evansito commented on src/documentation/pages/components/modal/examples/index.vue
> +      div(v-if="$store.state.themes.theme === 'portal'")
instead of v-if you could use v-else

2022-01-31 11:43 UTC, evansito commented on src/documentation/pages/components/modal/examples/_alert.vue
> +          active: true,
this is actually OK sorry, don't change it

2022-01-31 11:49 UTC, evansito commented on src/documentation/pages/components/modal/examples/_base.vue
> +  <ComponentExample title="Base" id="base" additionalClasses="-position--static" :tabs="exampleTabs">
it looks like there is no transition (the modal appears immediately while in the old documentation it takes a bit longer and it shows up from top page)

2022-01-31 11:54 UTC, evansito requested changes

2022-01-31 11:54 UTC, evansito commented on src/documentation/pages/components/modal/examples/index.vue
> +        <NoBorder />
these should be named ModalSubtitleLumenCenturyLink, InverseLumenCenturyLink etc

2022-01-31 11:54 UTC, evansito commented on src/documentation/pages/components/modal/examples/index.vue
> +        <Alert />
these should be named AlertPortal, MultiStepPortal

2022-01-31 11:54 UTC, evansito commented on src/documentation/pages/components/modal/examples/_subtitle.vue
> +export default class ModalSubtitle extends Vue {}
this should be named ModalSubtitleLumenCenturyLink, and the file name should be _subtitle-lumen-centurylink. Same for similar cases

2022-02-01 16:54 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/34/. :white_check_mark:

2022-02-01 16:54 UTC, SCMAUTO commented
You can check this PRs instance in https://d7475fb00906ddf7af41834439c0db29b0272477-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-267-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-02-01 17:28 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/35/. :white_check_mark:

2022-02-01 17:28 UTC, SCMAUTO commented
You can check this PRs instance in https://010ccb9f0e630d248dd21da56fc971f1cd5f37c6-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-267-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-02-03 09:26 UTC, josecarlosgonzalezv requested changes

2022-02-03 09:26 UTC, josecarlosgonzalezv commented on src/documentation/pages/components/modal/examples/_alert-portal.vue
> +declare const chi: any;
This const is never used.
```suggestion
```

2022-02-03 15:59 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/36/. :white_check_mark:

2022-02-03 15:59 UTC, SCMAUTO commented
You can check this PRs instance in https://39ab1c5248069b4017a972de8071c91eef052cbb-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-267-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-02-03 18:53 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/37/. :white_check_mark:

2022-02-03 18:53 UTC, SCMAUTO commented
You can check this PRs instance in https://027b3e0865c2fcbde6f00351a060e4c1bf307930-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-267-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-02-04 16:41 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/3/. :x:

2022-02-07 15:10 UTC, SCMAUTO commented
You can check this PRs instance in https://9d1abe59d8edd6bf006ed1b565a2eae383058ef6-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-267-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-02-07 17:03 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/5/. :white_check_mark:

2022-02-07 17:03 UTC, SCMAUTO commented
You can check this PRs instance in https://59ec6bfaca3b009e79140861fc53845e9242352a-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-267-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-02-09 10:49 UTC, josecarlosgonzalezv approved these changes

2022-02-09 12:05 UTC, jllr approved these changes

2022-02-09 12:07 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-267/6/. :white_check_mark:

2022-02-09 12:07 UTC, SCMAUTO commented
You can check this PRs instance in https://4c8daeb490a97f82a168f1d31dd7871b4b9ffb43-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-267-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-02-09 12:12 UTC, merged