[FSDE-11701] Migrate Link component to new Vue documentation
CenturyLink/Chi pull request #268
Opened 2021-12-20 11:18 UTC by josecarlosgonzalezv

2021-12-20 11:34 UTC, evansito commented on src/documentation/pages/components/link/examples/_base.vue
> +        <chi-link href="#">Link</chi-link>
```suggestion
      <chi-link href="#">Link</chi-link>
```

2021-12-20 11:35 UTC, evansito approved these changes

2021-12-20 11:55 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-268/1/. :white_check_mark:

2021-12-20 11:55 UTC, SCMAUTO commented
You can check this PRs instance in https://04e181be0eedd995b9fece6e8f28443944242ec7-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-268-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-20 12:31 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-268/2/. :white_check_mark:

2021-12-20 12:31 UTC, SCMAUTO commented
You can check this PRs instance in https://2394aaec4e8cdd5bc17a628d2016670325ebc526-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-268-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-21 08:37 UTC, jllr commented on src/documentation/pages/components/link/examples/_additional-sizes.vue
> +  <ComponentExample title="Additional Sizes" id="additional-sizes" :tabs="exampleTabs">
please add additional class `-text`

2021-12-21 08:37 UTC, jllr commented on src/documentation/pages/components/link/examples/_base.vue
> +  <ComponentExample title="Base" id="base" :tabs="exampleTabs">
please add additional class `-text`

2021-12-21 08:37 UTC, jllr commented on src/documentation/pages/components/link/examples/_cta.vue
> +  <ComponentExample title="CTA" id="cta" :tabs="exampleTabs">
please add additional class `-text`

2021-12-21 08:37 UTC, jllr commented on src/documentation/pages/components/link/examples/_disabled.vue
> +  <ComponentExample title="Disabled" id="disabled" :tabs="exampleTabs">
please add additional class `-text`

2021-12-21 08:37 UTC, jllr commented on src/documentation/pages/components/link/examples/_download.vue
> +  <ComponentExample title="Download" id="download" :tabs="exampleTabs">
please add additional class `-text`

2021-12-21 08:37 UTC, jllr commented on src/documentation/pages/components/link/examples/_hreflang.vue
> +  <ComponentExample title="Hreflang" id="hreflang" :tabs="exampleTabs">
please add additional class `-text`

2021-12-21 08:37 UTC, jllr commented on src/documentation/pages/components/link/examples/_icon-link.vue
> +  <ComponentExample title="Icon Link" id="icon-link" :tabs="exampleTabs">
please add additional class `-text`

2021-12-21 08:37 UTC, jllr commented on src/documentation/pages/components/link/examples/_labeled-icon-link.vue
> +  <ComponentExample title="Labeled Icon Link" id="labeled-icon-link" :tabs="exampleTabs">
please add additional class `-text`

2021-12-21 08:37 UTC, jllr commented on src/documentation/pages/components/link/examples/_no-hover-underline.vue
> +  <ComponentExample title="No Underline on Hover" id="noHoverUnderline" :tabs="exampleTabs">
please add additional class `-text`

2021-12-21 08:37 UTC, jllr commented on src/documentation/pages/components/link/examples/_rel.vue
> +  <ComponentExample title="Rel" id="rel" :tabs="exampleTabs">
please add additional class `-text`

2021-12-21 08:37 UTC, jllr commented on src/documentation/pages/components/link/examples/_target.vue
> +  <ComponentExample title="Target" id="target" :tabs="exampleTabs">
please add additional class `-text`

2021-12-21 10:32 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-268/3/. :white_check_mark:

2021-12-21 10:32 UTC, SCMAUTO commented
You can check this PRs instance in https://ef173747088b7bc4eadb0048d47faa1dcd3d64ed-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-268-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-22 13:02 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-268/4/. :x:

2021-12-22 14:55 UTC, evansito commented on src/documentation/pages/components/link/examples/_no-hover-underline.vue
> +  <ComponentExample title="No Underline on Hover" id="noHoverUnderline" :tabs="exampleTabs" additionalClasses="-text">
i'd recommend using the html convention of using dashes - for ids like in your other examples, e.g. no-hover-underline

2021-12-30 09:37 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-268/6/. :x:

2021-12-30 14:45 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-268/7/. :white_check_mark:

2021-12-30 14:45 UTC, SCMAUTO commented
You can check this PRs instance in https://27802a0ef7fe725db5ed0ecc5f684d9784ea1a40-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-268-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-04 09:52 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-268/8/. :white_check_mark:

2022-01-04 09:52 UTC, SCMAUTO commented
You can check this PRs instance in https://99dd6f6d8c33b969c703a7210b7b3e68df384f44-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-268-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-07 14:30 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-268/13/. :white_check_mark:

2022-01-07 14:30 UTC, SCMAUTO commented
You can check this PRs instance in https://16e0d8e3a1ca09b0fedd87d6192dba2f0a0f1a06-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-268-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-10 11:04 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-268/15/. :x:

2022-01-10 14:36 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-268/16/. :x:

2022-01-10 15:07 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-268/17/. :x:

2022-01-12 12:53 UTC, jllr requested changes

2022-01-12 12:53 UTC, jllr commented on src/documentation/pages/components/link/_accessibility.vue
> +  <div>
```suggestion
  div
```

2022-01-12 12:53 UTC, jllr commented on src/documentation/pages/components/link/_accessibility.vue
> +  </div>
```suggestion
```

2022-01-12 12:53 UTC, jllr commented on src/documentation/pages/components/link/_properties.vue
> +  <div>
```suggestion
  div
```

2022-01-12 12:53 UTC, jllr commented on src/documentation/pages/components/link/_properties.vue
> +  </div>
```suggestion
```

2022-01-12 12:53 UTC, jllr commented on src/documentation/pages/components/link/examples/index.vue
> +  <div>
```suggestion
  div
```

2022-01-12 12:53 UTC, jllr commented on src/documentation/pages/components/link/examples/index.vue
> +  </div>
```suggestion
```

2022-01-12 13:27 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-268/18/. :white_check_mark:

2022-01-12 13:27 UTC, SCMAUTO commented
You can check this PRs instance in https://27ea56d75d59f7140f8d23042f6114430c9ea1a1-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-268-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-13 10:03 UTC, jllr approved these changes

2022-01-13 10:20 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-268/20/. :white_check_mark:

2022-01-13 10:20 UTC, SCMAUTO commented
You can check this PRs instance in https://e8d93855c24ec1beb6aba1fbcda3fbfa852be203-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-268-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-13 10:21 UTC, merged