[FSDE-12154] Migrate Pagination component examples to new documentation
CenturyLink/Chi pull request #274
Opened 2021-12-29 16:25 UTC by josecarlosgonzalezv

2021-12-29 17:07 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-274/1/. :white_check_mark:

2021-12-29 17:07 UTC, SCMAUTO commented
You can check this PRs instance in https://307121a770f283f539effedfd461e075e91f3ed7-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-274-ux-chi.kubeodc-test.corp.intranet/ (internal)

2021-12-30 09:55 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-274/2/. :white_check_mark:

2021-12-30 09:55 UTC, SCMAUTO commented
You can check this PRs instance in https://bbd88bc6b0ba09c7e24f5686bb62e0d3f2372d56-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-274-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-10 10:42 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-274/5/. :white_check_mark:

2022-01-10 10:42 UTC, SCMAUTO commented
You can check this PRs instance in https://80aa223d263fa426610d71d846934e05e22e509c-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-274-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-10 12:05 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-274/6/. :white_check_mark:

2022-01-10 12:05 UTC, SCMAUTO commented
You can check this PRs instance in https://f80eff8be7baa294f3109247a7a450027a960bcf-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-274-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-10 14:13 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-274/7/. :x:

2022-01-10 15:15 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-274/8/. :white_check_mark:

2022-01-10 15:15 UTC, SCMAUTO commented
You can check this PRs instance in https://d9d6e34c33260c2385086c1eff28430f6985ecbf-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-274-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-11 11:14 UTC, evansito requested changes

2022-01-11 11:14 UTC, evansito commented on src/documentation/pages/components/pagination/examples/_additional-sizes.vue
> +  <ComponentExample title="Additional Sizes" id="additional_sizes" :tabs="exampleTabs" padding="-p--0">
i'd recommend using dashes additional-sizes as per html id standards

2022-01-11 11:14 UTC, evansito commented on src/documentation/pages/components/pagination/examples/_additional-sizes.vue
> +    <Wrapper slot="example">
no need for wrapper here, slot="example" could go in the below div as it's 1 child

2022-01-11 11:14 UTC, evansito commented on src/documentation/pages/components/pagination/examples/_additional-sizes.vue
> +</script>
looks like this file needs a new line at the end

2022-01-11 11:14 UTC, evansito commented on src/documentation/pages/components/pagination/examples/_base.vue
> +    <Wrapper slot="example">
same here and the rest of cases like this

2022-01-11 11:14 UTC, evansito commented on src/documentation/pages/components/pagination/examples/_base.vue
> +</script>
new line

2022-01-11 11:14 UTC, evansito commented on src/documentation/pages/components/pagination/examples/_double-truncation.vue
> +  <ComponentExample title="Double Truncation" id="double_truncation" :tabs="exampleTabs" padding="-p--0">
same here

2022-01-11 11:14 UTC, evansito commented on src/documentation/pages/components/pagination/examples/_double-truncation.vue
> +</script>
new line

2022-01-11 11:14 UTC, evansito commented on src/documentation/pages/components/pagination/examples/_results-label.vue
> +  <ComponentExample title="Results Label" id="results_label" :tabs="exampleTabs" padding="-p--0">
same

2022-01-11 11:14 UTC, evansito commented on src/documentation/pages/components/pagination/examples/_results-label.vue
> +</script>
same

2022-01-11 11:14 UTC, evansito commented on src/documentation/pages/components/pagination/examples/portal/_base.vue
> +export default class Base extends Vue {}
should be named BasePortal

2022-01-11 11:14 UTC, evansito commented on src/documentation/pages/components/pagination/examples/index.vue
> +      <Portal />
should be imported as BasePortal

2022-01-11 11:14 UTC, evansito commented on src/documentation/pages/components/pagination/examples/portal/_results-label.vue
> +})
should be named ResultsLabelPortal

2022-01-11 11:14 UTC, evansito commented on src/documentation/pages/components/pagination/index.vue
> +  <div>
could be written as pug's div (without <>)

2022-01-11 13:04 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-274/9/. :white_check_mark:

2022-01-11 13:04 UTC, SCMAUTO commented
You can check this PRs instance in https://3573bd2a71b119795d99aca9435589550386f961-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-274-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-12 22:39 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-274/1/. :white_check_mark:

2022-01-12 22:39 UTC, SCMAUTO commented
You can check this PRs instance in https://5f5cd73c181e2d9d57f8e4250fc00acab7292252-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-274-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-13 12:02 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-274/4/. :white_check_mark:

2022-01-13 12:02 UTC, SCMAUTO commented
You can check this PRs instance in https://6f278a73991e03eff992f045730f9dcfcfb80866-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-274-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-13 22:56 UTC, soujanreddy requested changes

2022-01-13 22:56 UTC, soujanreddy commented on src/documentation/pages/components/pagination/examples/_additional-sizes_lumen_centurylink.vue
> +  <ComponentExample title="Additional Sizes" id="additional_sizes_lumen_centurylink" :tabs="exampleTabs" padding="-p--0">
To maintain consistency, you can update to kebab-case for id's. I see we are using kebab-case through out the code.

2022-01-13 22:56 UTC, soujanreddy commented on src/documentation/pages/components/pagination/examples/_base_lumen_centurylink.vue
> +  <ComponentExample title="Base" id="base_lumen_centurylink" :tabs="exampleTabs" padding="-p--0">
Same here

2022-01-13 22:56 UTC, soujanreddy commented on src/documentation/pages/components/pagination/examples/_compact/_base_lumen_centurylink.vue
> +  <ComponentExample title="Base" id="base_compact_lumen_centurylink" :tabs="exampleTabs" padding="-p--0" titleSize="h4">
You can update for all id's.

2022-01-14 11:30 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-274/5/. :white_check_mark:

2022-01-14 11:30 UTC, SCMAUTO commented
You can check this PRs instance in https://4187abeb04f83da7072947f2f97e5347fe688742-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-274-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-14 17:24 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-274/7/. :x:

2022-01-17 10:15 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-274/8/. :x:

2022-01-17 12:03 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-274/9/. :white_check_mark:

2022-01-17 12:03 UTC, SCMAUTO commented
You can check this PRs instance in https://75de984c78a498728cbaa3b9059289f25b8bd417-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-274-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-17 12:49 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-274/10/. :white_check_mark:

2022-01-17 12:49 UTC, SCMAUTO commented
You can check this PRs instance in https://bd3a34de434ff8f635114d1ffa29b9d778436ea1-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-274-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-17 13:33 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-274/11/. :white_check_mark:

2022-01-17 13:33 UTC, SCMAUTO commented
You can check this PRs instance in https://b115ff39266bb2290025109d0ff894945a3d3668-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-274-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-17 14:59 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-274/12/. :white_check_mark:

2022-01-17 14:59 UTC, SCMAUTO commented
You can check this PRs instance in https://1ff52f95556a9be3f03a50162bb86310da3f9790-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-274-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-17 15:20 UTC, jllr requested changes

2022-01-17 15:20 UTC, jllr commented on src/documentation/pages/components/pagination/examples/_compact/_page-jumper_lumen_centurylink.vue
> +        htmlblueprint: `<!-- For light backgrounds -->
Missing dark backgrounds example

2022-01-17 15:20 UTC, jllr commented on src/documentation/pages/components/pagination/examples/_page-size_lumen_centurylink.vue
> +          chi-pagination(pages="12" current-page="3" page-size)
Missing results in page size

2022-01-17 15:20 UTC, jllr commented on src/documentation/pages/components/pagination/examples/_portal/_results-label.vue
> +          chi-pagination(pages="12" current-page="3" size="xs" results="240")
Example is not compact

2022-01-17 15:20 UTC, jllr commented on src/documentation/pages/components/pagination/examples/_results-label_lumen_centurylink.vue
> +<!-- For light backgrounds -->
Dark bg, not light. Please review code snippets

2022-01-18 11:00 UTC, SCMAUTO commented
You can check this PRs instance in https://875de1f335446e307121ba6b3a743899aa919080-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-274-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-18 12:17 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-274/14/. :white_check_mark:

2022-01-18 12:17 UTC, SCMAUTO commented
You can check this PRs instance in https://31bc8e5f1c1d0bdbf8e47076535c61b6b8a41934-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-274-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-18 12:50 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-274/15/. :white_check_mark:

2022-01-18 12:50 UTC, SCMAUTO commented
You can check this PRs instance in https://875de1f335446e307121ba6b3a743899aa919080-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-274-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-01-26 14:49 UTC, evansito requested changes

2022-01-26 14:49 UTC, evansito commented on src/documentation/pages/components/pagination/_accessibility.vue
> +  div
AccessibilityComingSoon component

2022-01-26 14:49 UTC, evansito commented on src/documentation/pages/components/pagination/examples/_additional-sizes_lumen_centurylink.vue
> +      string: 'String',
this should be removed

2022-01-26 14:49 UTC, evansito commented on src/documentation/pages/components/pagination/examples/_base_lumen_centurylink.vue
> +      string: 'String',
same here and in further examples

2022-01-26 14:49 UTC, evansito commented on src/documentation/pages/components/pagination/examples/_compact/_base_lumen_centurylink.vue
> +</script>
no newline at end of file

2022-01-26 14:49 UTC, evansito commented on src/documentation/pages/components/pagination/examples/_compact/_first-last-page-buttons_lumen_centurylink.vue
> +</script>
no new line at end of file

2022-01-26 14:49 UTC, evansito commented on src/documentation/pages/components/pagination/examples/_compact/_page-jumper_lumen_centurylink.vue
> +</script>
no new line at end of file

2022-01-26 14:49 UTC, evansito commented on src/documentation/pages/components/pagination/examples/_page-jumper_lumen_centurylink.vue
> +</script>
no new line at end of file

2022-01-26 14:49 UTC, evansito commented on src/documentation/pages/components/pagination/examples/_page-size_lumen_centurylink.vue
> +</script>
no new line at end of file

2022-01-26 14:49 UTC, evansito commented on src/documentation/pages/components/pagination/examples/_additional-sizes_lumen_centurylink.vue
> +export default class AdditionalSizesLumenCenturylink extends Vue {}
I believe L in link is uppercase, i.e. CenturyLink. Please change this in all examples

2022-01-26 14:49 UTC, evansito commented on src/documentation/pages/components/pagination/examples/_portal/_base.vue
> +</script>
no new line at end of file

2022-01-26 14:49 UTC, evansito commented on src/documentation/pages/components/pagination/examples/_portal/_results-label.vue
> +</script>
no new line at end of file

2022-01-27 14:03 UTC, evansito commented on src/documentation/pages/components/pagination/examples/index.vue
> +    div(v-if="$store.state.themes.theme === 'portal'")
v-else

2022-01-27 14:06 UTC, evansito commented on src/documentation/pages/components/pagination/examples/_disabled_lumen_centurylink.vue
> +      .chi-col.-w--12.-w-md--6
v-for loop could be used here

2022-01-27 22:01 UTC, soujanreddy approved these changes

2022-02-01 12:02 UTC, jllr approved these changes

2022-02-01 12:04 UTC, janibolkvadze approved these changes

2022-02-01 12:41 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-274/20/. :white_check_mark:

2022-02-01 12:41 UTC, SCMAUTO commented
You can check this PRs instance in https://cbba626aa706ed2afd497e383710639876804d6f-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-274-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-02-01 12:44 UTC, merged