Migrate Toggle switch component to new vue documentation
CenturyLink/Chi pull request #327
Opened 2022-02-14 19:50 UTC by soujanreddy

@jllr We need a ticket number for this component.

2022-02-15 10:49 UTC, josecarlosgonzalezv approved these changes

2022-02-16 11:07 UTC, evansito requested changes

2022-02-16 11:07 UTC, evansito commented on src/documentation/pages/components/forms/toggle-switch/examples/_inline-lumen-centurylink.vue
> +  <ComponentExample title="Inline" id="inline-portal" :tabs="exampleTabs">
this should be inline-lumen-centurylink

2022-02-16 11:07 UTC, evansito commented on src/documentation/pages/components/forms/toggle-switch/examples/_portal/_base-portal.vue
> +export default class BasePortal extends Vue {}
this file doesn't need to be named base-portal, as it's inside a portal folder, you can name it just _base

2022-02-16 11:07 UTC, evansito commented on src/documentation/pages/components/forms/toggle-switch/examples/_portal/_checked-portal.vue
> +export default class CheckedPortal extends Vue {}
Same here and in other similar files within portal/

2022-02-22 11:51 UTC, evansito requested changes

2022-02-22 21:48 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-327/6/. :white_check_mark:

2022-02-22 21:48 UTC, SCMAUTO commented
You can check this PRs instance in https://21c6509472cb5c27c2cfe2c946ed6da352d458e8-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-327-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-02-23 16:27 UTC, evansito approved these changes

2022-02-23 17:33 UTC, jllr requested changes

2022-02-23 17:33 UTC, jllr commented on src/documentation/pages/components/forms/toggle-switch/examples/_portal/_sizes.vue
> +      | The default size is <code>sm</code>.
```suggestion
      | The default size is <code>xs</code>.
```

2022-02-23 17:35 UTC, jllr approved these changes

2022-02-23 17:46 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-327/7/. :white_check_mark:

2022-02-23 17:46 UTC, SCMAUTO commented
You can check this PRs instance in https://89e4f31b877ca18edfdc46d75c8484f2415fc45f-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-327-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-02-23 18:17 UTC, SCMAUTO commented
You can check this PRs instance in https://11b57e5022eae091efe4096979f55975508f66e6-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-327-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-02-24 10:49 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-327/9/. :white_check_mark:

2022-02-24 10:49 UTC, SCMAUTO commented
You can check this PRs instance in https://b989cf354530ddb6718670ee28b2ecef8b03fafc-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-327-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-02-24 11:00 UTC, merged