[FSDE-16082] Migrate Button group component to vue documentation
CenturyLink/Chi pull request #339
Opened 2022-02-25 02:13 UTC by soujanreddy

2022-02-25 22:13 UTC, soujanreddy commented
@jllr Can you provide a ticket number for this component.

2022-03-02 16:24 UTC, evansito requested changes

2022-03-02 16:24 UTC, evansito commented on src/documentation/components/Navigation.vue
> +          <li><NuxtLink to="/components/button">Button</NuxtLink></li>
the button addition does not belong to this PR

2022-03-02 16:24 UTC, evansito commented on src/documentation/pages/components/button-group/examples/_portal/_hybrid-sizes.vue
> +export default class HybridSizes extends Vue {}
HybridSizesPortal

2022-03-02 16:24 UTC, evansito commented on src/documentation/pages/components/button-group/examples/_portal/_sizes-horizontal.vue
> +    .-p--0(slot="example" v-for="size in sizes")
padding can be added as prop instead of in the below div

2022-03-02 16:24 UTC, evansito commented on src/documentation/pages/components/button-group/examples/_portal/_sizes-horizontal.vue
> +export default class SizesHorizontal extends Vue {}
SizesHorizontalPortal

2022-03-02 16:24 UTC, evansito commented on src/documentation/pages/components/button-group/examples/_portal/_sizes-vertical.vue
> +    .-p--0(slot="example" v-for="size in sizes")
same here

2022-03-02 16:24 UTC, evansito commented on src/documentation/pages/components/button-group/examples/_portal/_sizes-vertical.vue
> +export default class SizesVertical extends Vue {}
SizesVerticalPortal

2022-03-02 16:24 UTC, evansito commented on src/documentation/pages/components/button-group/examples/index.vue
> +      <HybridSizes />
These should be named as SizesHorizontalPortal, SizesVerticalPortal etc

2022-03-02 16:24 UTC, evansito commented on src/documentation/pages/components/button-group/index.vue
> +Vue.config.ignoredElements = ['chi-icon', 'chi-button'];
is chi-brand not needed?

2022-03-02 16:41 UTC, soujanreddy commented on src/documentation/pages/components/button-group/index.vue
> +Vue.config.ignoredElements = ['chi-icon', 'chi-button'];
Yes, it is not needed.

2022-03-04 16:44 UTC, soujanreddy commented on src/documentation/pages/components/button-group/examples/_hybrid-sizes-lumen-centurylink.vue
> +  <ComponentExample titleSize="h4" title="Hybrid buttons sizes" id="hybrid-buttons-sizes-lumen-centurylink" :tabs="exampleTabs">
Good catch!

2022-03-04 17:24 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-339/6/. :white_check_mark:

2022-03-04 17:24 UTC, SCMAUTO commented
You can check this PRs instance in https://a21972b2012c423b9c71da07b811f0dea28b9d7c-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-339-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-03-04 17:53 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-339/7/. :white_check_mark:

2022-03-04 17:54 UTC, SCMAUTO commented
You can check this PRs instance in https://6de9d0da68c239a8c460daac542ae83f8ca66d79-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-339-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-03-07 09:38 UTC, josecarlosgonzalezv approved these changes

2022-03-08 18:37 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-339/8/. :x:

2022-03-09 18:44 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-339/9/. :white_check_mark:

2022-03-09 18:44 UTC, SCMAUTO commented
You can check this PRs instance in https://e536f6d22e69aa40d5fbf90cc7ea3c9959327356-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-339-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-03-10 22:52 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-339/10/. :white_check_mark:

2022-03-10 22:53 UTC, SCMAUTO commented
You can check this PRs instance in https://fe7e9d2891b180e97ed3702baa02b4e43f6e7b70-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-339-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-03-11 16:03 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-339/11/. :white_check_mark:

2022-03-11 16:03 UTC, SCMAUTO commented
You can check this PRs instance in https://89aaa91548c1328cb345fbee83eeff7f761fbd22-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-339-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-03-16 22:34 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-339/14/. :white_check_mark:

2022-03-16 22:34 UTC, SCMAUTO commented
You can check this PRs instance in https://f359cbd7a7c408065646c907642b88ed3f6c8760-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-339-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-03-17 16:04 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-339/15/. :x:

2022-03-21 17:31 UTC, SCMAUTO commented
You can check this PRs instance in https://f7c857730e73d40509c4deb2cebef2777e47d7a2-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-339-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-03-31 11:25 UTC, jllr commented
@soujanreddy solve conflicts and send the PR again

2022-03-31 15:13 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-339/17/. :x:

2022-04-01 16:41 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-339/18/. :white_check_mark:

2022-04-01 16:41 UTC, SCMAUTO commented
You can check this PRs instance in https://4c5826db4c32fa00bd60791588c253b43920f7a4-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-339-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-04-04 10:06 UTC, merged