Migrate Activity component to vue documentation
CenturyLink/Chi pull request #343
Opened 2022-03-03 02:13 UTC by soujanreddy

2022-03-03 08:53 UTC, evansito requested changes

2022-03-03 08:53 UTC, evansito commented on src/documentation/components/Navigation.vue
>          <div class="chi-collection__title">Components</div>
the above avatar image shouldn't be in this PR

2022-03-03 08:53 UTC, evansito commented on src/documentation/pages/components/activity/examples/_with-avatar.vue
> +                  | Admin
could we use a v-for loop here?

2022-03-03 08:53 UTC, evansito commented on src/documentation/pages/components/activity/examples/index.vue
> +      | To render an avatar, use the class <code>chi-activity</code>.
To render an activity, not avatar

2022-03-03 20:44 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-343/3/. :white_check_mark:

2022-03-03 20:44 UTC, SCMAUTO commented
You can check this PRs instance in https://2b2e87d30919e36b82c15e37eb0a6eda70bcc854-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-343-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-03-04 00:40 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-343/4/. :x:

2022-03-04 01:09 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-343/5/. :white_check_mark:

2022-03-04 01:09 UTC, SCMAUTO commented
You can check this PRs instance in https://95dea065fe0b845cb1755970185757a7b7683e2e-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-343-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-03-04 09:18 UTC, josecarlosgonzalezv approved these changes

2022-03-04 16:10 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-343/6/. :white_check_mark:

2022-03-04 16:10 UTC, SCMAUTO commented
You can check this PRs instance in https://ca72ef42c83f218f95c1528cef582b3be9e8a3c7-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-343-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-03-08 18:29 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-343/7/. :x:

2022-03-09 10:09 UTC, evansito approved these changes

2022-03-09 17:50 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-343/8/. :white_check_mark:

2022-03-09 17:50 UTC, SCMAUTO commented
You can check this PRs instance in https://d75f049ec1b9d04fa0a3e58d8467834a09b7c77a-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-343-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-03-09 18:37 UTC, jllr approved these changes

2022-03-09 18:38 UTC, merged