[FSDE-16823] Improve printing methods for child and grand child rows in data table
CenturyLink/Chi pull request #354
Opened 2022-03-15 15:27 UTC by josecarlosgonzalezv

2022-03-15 15:39 UTC, janibolkvadze requested changes

2022-03-15 15:39 UTC, janibolkvadze commented on src/chi-vue/src/components/data-table/DataTable.tsx
> +  printMode = this.$props.config?.print?.mode || defaultConfig.print?.mode;
```suggestion
  printMode = this.$props.config?.print?.mode || defaultConfig.print.mode;
```
We control the `defaulctConfig` so it must be set always 😉

2022-03-15 16:14 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-354/1/. :white_check_mark:

2022-03-15 16:14 UTC, SCMAUTO commented
You can check this PRs instance in https://c673d4e3b7f9272cc83fb4b73f4852fb080060ab-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-354-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-03-16 09:58 UTC, janibolkvadze approved these changes

2022-03-16 10:52 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-354/3/. :white_check_mark:

2022-03-16 10:52 UTC, SCMAUTO commented
You can check this PRs instance in https://8776c75fed0266a0abbc170e5bc49ee574d4940e-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-354-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-03-16 12:14 UTC, jllr approved these changes

2022-03-16 12:15 UTC, merged