[FSDE-17745] Implemented code snippets for checkbox webcomponent
CenturyLink/Chi pull request #363
Opened 2022-03-29 23:16 UTC by soujanreddy

2022-03-29 23:42 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-363/1/. :white_check_mark:

2022-03-29 23:42 UTC, SCMAUTO commented
You can check this PRs instance in https://ff59cdb52959089e5fd0f3315278e29bd6da73be-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-363-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-04-04 09:37 UTC, josecarlosgonzalezv requested changes

2022-04-04 09:37 UTC, josecarlosgonzalezv commented on src/website/views/components/forms/checkbox/_examples.pug
> +      <chi-checkbox id="checkbox-dis1" label="Checkbox" disabled></chi-checkbox>
I would use the same IDs as in the HTLM Blueprint.
```suggestion
      <chi-checkbox id="checkbox-di1" label="Checkbox" disabled></chi-checkbox>
```

2022-04-04 09:37 UTC, josecarlosgonzalezv commented on src/website/views/components/forms/checkbox/_examples.pug
> +      <chi-checkbox id="checkbox-ms1" label="Checkbox"></chi-checkbox>
I would use the same IDs as in the HTLM Blueprint.
```suggestion
      <chi-checkbox id="checkbox-me1" label="Checkbox"></chi-checkbox>
```

2022-04-04 09:37 UTC, josecarlosgonzalezv commented on src/website/views/components/forms/checkbox/_examples.pug
> +            <chi-checkbox id="checkbox-gr12" label="Option 12"></chi-checkbox>
```suggestion
            <chi-checkbox id="checkbox-g1" label="Option 1"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g2" label="Option 2"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g3" label="Option 3"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g4" label="Option 4"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g5" label="Option 5"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g6" label="Option 6"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g7" label="Option 7"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g8" label="Option 8"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g9" label="Option 9"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g10" label="Option 10"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g11" label="Option 11"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g12" label="Option 12"></chi-checkbox>
```

2022-04-04 09:37 UTC, josecarlosgonzalezv commented on src/website/views/components/forms/checkbox/_examples.pug
> +            <chi-checkbox id="checkbox-gr12" label="Option 12"></chi-checkbox>
I would use the same IDs as in the HTLM Blueprint.
```suggestion
            <chi-checkbox id="checkbox-g1" label="Option 1"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g2" label="Option 2"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g3" label="Option 3"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g4" label="Option 4"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g5" label="Option 5"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g6" label="Option 6"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g7" label="Option 7"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g8" label="Option 8"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g9" label="Option 9"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g10" label="Option 10"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g11" label="Option 11"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g12" label="Option 12"></chi-checkbox>
```

2022-04-04 09:37 UTC, josecarlosgonzalezv commented on src/website/views/components/forms/checkbox/_examples.pug
> +            <chi-checkbox id="checkbox-gr12" label="Option 12"></chi-checkbox>
I would use the same IDs as in the HTLM Blueprint.
```suggestion
            <chi-checkbox id="checkbox-g1" label="Option 1"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g2" label="Option 2"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g3" label="Option 3"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g4" label="Option 4"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g5" label="Option 5"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g6" label="Option 6"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g7" label="Option 7"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g8" label="Option 8"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g9" label="Option 9"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g10" label="Option 10"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g11" label="Option 11"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g12" label="Option 12"></chi-checkbox>
```

2022-04-04 09:37 UTC, josecarlosgonzalezv commented on src/website/views/components/forms/checkbox/_examples.pug
> +            <chi-checkbox id="checkbox-gr12" label="Option 12"></chi-checkbox>
I would use the same IDs as in the HTLM Blueprint.
```suggestion
            <chi-checkbox id="checkbox-g1" label="Option 1"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g2" label="Option 2"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g3" label="Option 3"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g4" label="Option 4"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g5" label="Option 5"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g6" label="Option 6"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g7" label="Option 7"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g8" label="Option 8"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g9" label="Option 9"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g10" label="Option 10"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g11" label="Option 11"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g12" label="Option 12"></chi-checkbox>
```

2022-04-04 09:37 UTC, josecarlosgonzalezv commented on src/website/views/components/forms/checkbox/_examples.pug
> +            <chi-checkbox id="checkbox-gr12" label="Option 12"></chi-checkbox>
I would use the same IDs as in the HTLM Blueprint.
```suggestion
            <chi-checkbox id="checkbox-g1" label="Option 1"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g2" label="Option 2"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g3" label="Option 3"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g4" label="Option 4"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g5" label="Option 5"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g6" label="Option 6"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g7" label="Option 7"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g8" label="Option 8"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g9" label="Option 9"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g10" label="Option 10"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g11" label="Option 11"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g12" label="Option 12"></chi-checkbox>
```

2022-04-04 09:37 UTC, josecarlosgonzalezv commented on src/website/views/components/forms/checkbox/_examples.pug
> +            <chi-checkbox id="checkbox-gr12" label="Option 12"></chi-checkbox>
I would use the same IDs as in the HTLM Blueprint.
```suggestion
            <chi-checkbox id="checkbox-g1" label="Option 1"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g2" label="Option 2"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g3" label="Option 3"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g4" label="Option 4"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g5" label="Option 5"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g6" label="Option 6"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g7" label="Option 7"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g8" label="Option 8"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g9" label="Option 9"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g10" label="Option 10"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g11" label="Option 11"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g12" label="Option 12"></chi-checkbox>
```

2022-04-04 09:39 UTC, josecarlosgonzalezv requested changes

2022-04-04 09:39 UTC, josecarlosgonzalezv commented on src/website/views/components/forms/checkbox/_examples.pug
> +            <chi-checkbox id="checkbox-gr12" label="Option 12"></chi-checkbox>
I would use the same IDs as in the HTLM Blueprint.
```suggestion
            <chi-checkbox id="checkbox-g1" label="Option 1"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g2" label="Option 2"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g3" label="Option 3"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g4" label="Option 4"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g5" label="Option 5"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g6" label="Option 6"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g7" label="Option 7"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g8" label="Option 8"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g9" label="Option 9"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g10" label="Option 10"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g11" label="Option 11"></chi-checkbox>
          </div>
        </div>
        <div class="chi-col -w--12 -w-md--3 -w-sm--6 -mb--1">
          <div class="chi-form__item">
            <chi-checkbox id="checkbox-g12" label="Option 12"></chi-checkbox>
```

2022-04-05 15:18 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-363/2/. :white_check_mark:

2022-04-06 18:29 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-363/3/. :white_check_mark:

2022-04-06 18:29 UTC, SCMAUTO commented
You can check this PRs instance in https://a47447cf3e4e23c079b4027170dba7f2e7ef0b6c-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-363-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-04-07 22:55 UTC, soujanreddy commented
@jllr This PR is not getting updated with my new commits for some reason. Closing this and reopening a new PR with the updated changes.

2022-04-07 22:55 UTC, closed without merging

2022-04-07 23:39 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-363/4/. :white_check_mark:

2022-04-07 23:39 UTC, SCMAUTO commented
You can check this PRs instance in https://507c55e19eae9bc59c674e7dbf0574fadc90e518-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-363-ux-chi.kubeodc-test.corp.intranet/ (internal)