[FSDE-17717] Html blueprint for Edit ribbon
CenturyLink/Chi pull request #388
Opened 2022-05-19 08:37 UTC by jllr

https://ctl.atlassian.net/browse/FSDE-17717

2022-05-19 09:25 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-388/1/. :white_check_mark:

2022-05-19 09:26 UTC, SCMAUTO commented
You can check this PRs instance in https://49055c4265ff24d722724a3638d32b2223bda5d3-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-388-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-06-01 12:21 UTC, SCMAUTO commented
You can check this PRs instance in https://54428a3208f4ea83cdca9cfc7ffb13097a1a1116-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-388-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-06-06 12:18 UTC, SCMAUTO commented
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-388/3/. :white_check_mark:

2022-06-06 12:18 UTC, SCMAUTO commented
You can check this PRs instance in https://bcbb53a4cb33a5f03ddd6acdb2451311c01354fb-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-388-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-06-06 18:48 UTC, mattnickles commented on src/chi/components/save-view/save-view.scss
> +    border: 0.0625rem dashed $save-view-save-border-color;
In addition to the color can we theme the border style?

2022-06-06 19:27 UTC, mattnickles commented on src/chi/components/save-view/save-view.scss
> +    background-color: #0075c9;
We'll need to create a variable e.g. $save-view-ribbon-background-color and apply it both here and the arrow after border color value. $color-background-primary should work as the variable value for all themes except Brightspeed.

2022-06-07 16:09 UTC, SCMAUTO commented
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-388/4/. :white_check_mark:

2022-06-07 16:09 UTC, SCMAUTO commented
You can check this PRs instance in https://78a77b01ad07a8b133d6e3327f0b8d4209c499be-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-388-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-06-08 10:11 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-388/5/. :x:

2022-06-08 11:18 UTC, SCMAUTO commented
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-388/6/. :white_check_mark:

2022-06-08 11:18 UTC, SCMAUTO commented
You can check this PRs instance in http://b422fd01ef2ebdb096c1b7d537f291a685bd6c82-chi-pr-po-ctl.s3-website-us-east-1.amazonaws.com (external) and in https://nginx-pr-388-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-06-08 11:20 UTC, janibolkvadze approved these changes

2022-06-08 22:59 UTC, mattnickles requested changes

2022-06-08 22:59 UTC, mattnickles commented on src/chi/themes/brightspeed/_variables.scss
> +$save-view-ribbon-arrow-border-color:       $color-blue-70;
We can't render the Lumen blue color in the Brightspeed theme. I would recommend using black.

```suggestion
$save-view-ribbon-background-color:         $color-black;
$save-view-ribbon-label-color:              $color-text-white;
$save-view-ribbon-label-font-style:         italic;
$save-view-ribbon-arrow-border-color:       $color-black;
```

2022-06-09 09:27 UTC, SCMAUTO commented
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-388/7/. :white_check_mark:

2022-06-09 09:27 UTC, SCMAUTO commented
You can check this PRs instance in http://228745c8323b52575dfa900094366f16c8bb1e83-chi-pr-po-ctl.s3-website-us-east-1.amazonaws.com (external) and in https://nginx-pr-388-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-06-09 10:02 UTC, SCMAUTO commented
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-388/8/. :white_check_mark:

2022-06-09 10:02 UTC, SCMAUTO commented
You can check this PRs instance in http://8e6f66540878acd97499a0a9962e9c6f0152934f-chi-pr-po-ctl.s3-website-us-east-1.amazonaws.com (external) and in https://nginx-pr-388-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-06-09 19:04 UTC, mattnickles approved these changes

2022-06-10 10:27 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-388/9/. :x:

2022-06-10 12:45 UTC, SCMAUTO commented
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-388/10/. :white_check_mark:

2022-06-10 12:45 UTC, SCMAUTO commented
You can check this PRs instance in http://e8f3304dc7d3eac555fe862e02ae37f8082301de-chi-pr-po-ctl.s3-website-us-east-1.amazonaws.com (external) and in https://nginx-pr-388-ux-chi.kubeodc-test.corp.intranet/ (internal)

2022-06-10 12:58 UTC, merged