[FSDE-23465] Add e2e tests for Chi vue expansion panel
CenturyLink/Chi pull request #431
Opened 2022-07-15 21:11 UTC by soujanreddy

2022-07-19 15:03 UTC, josecarlosgonzalezv commented on test/chi/chi-vue/expansion-panel.pug
> +        div(slot='footer')
This footer does not look good.

![image](https://user-images.githubusercontent.com/86958774/179781211-1115830b-d47f-463b-be33-d9bf4a73c89a.png)

Also, you are using this `footer-start-slot` class to find the slot. You may not need these classes, just try to find the slots using another way. Is this correct? @janibolkvadze ?

https://docs.cypress.io/guides/component-testing/slots-vue

2022-07-20 16:45 UTC, josecarlosgonzalezv approved these changes

2022-07-21 10:34 UTC, janibolkvadze requested changes

2022-07-21 10:34 UTC, janibolkvadze commented on cypress/integration/chi-vue/expansion-panel.spec.js
> +      cy.get(EXPANSION_PANEL_DATA_CY.BASE.EXPANSION_PANEL_FIRST)
We need to use aliases, like:
`.as('firstExpansionPanel')`

and then

`.get('@firstExpansionPanel')`

2022-07-21 10:34 UTC, janibolkvadze commented on cypress/integration/chi-vue/expansion-panel.spec.js
> +      // Given - first panel is active/open and second panel is collapsed/pending
We don't usually use comments in test cases. The descriptions need to be descriptive enough.

2022-07-21 10:34 UTC, janibolkvadze commented on cypress/integration/chi-vue/expansion-panel.spec.js
> +      cy.get(EXPANSION_PANEL_DATA_CY.BASE.EXPANSION_PANEL_FIRST)
Performing similar actions for several components can be placed in a forEach.

2022-07-21 10:34 UTC, janibolkvadze commented on cypress/integration/chi-vue/expansion-panel.spec.js
> +      cy.get(EXPANSION_PANEL_DATA_CY.BASE.EXPANSION_PANEL_FIRST)
Assertions as well can be placed in iterations as well.

2022-07-21 10:34 UTC, janibolkvadze commented on cypress/integration/chi-vue/expansion-panel.spec.js
> +      cy.get(EXPANSION_PANEL_DATA_CY.BASE.EXPANSION_PANEL_FIRST)
Example: line 159 in `data-table.spec.js`

2022-07-21 10:34 UTC, janibolkvadze commented on cypress/integration/chi-vue/expansion-panel.spec.js
> +
```suggestion
```

2022-07-21 14:08 UTC, jllr commented
@soujanreddy suggestions have been made by @josecarlosgonzalezv

2022-07-22 11:09 UTC, janibolkvadze approved these changes

2022-07-22 11:10 UTC, jllr approved these changes

2022-07-22 11:11 UTC, merged