[FSDE-24708] Include Save view component in New Vue documentation
CenturyLink/Chi pull request #437
Opened 2022-08-02 12:02 UTC by josecarlosgonzalezv

2022-08-10 16:15 UTC, jllr approved these changes

2022-08-19 11:21 UTC, janibolkvadze commented on src/documentation/package-lock.json
> +      "integrity": "sha1-l6ERlkmyEa0zaR2fn0hqjsn74KM="
Package-lock file should not be changed here.

2022-08-19 11:21 UTC, janibolkvadze commented on src/documentation/package.json
> +    "@centurylink/chi-vue": "1.5.0",
1.5.1

2022-08-19 11:25 UTC, janibolkvadze requested changes

2022-08-19 11:25 UTC, janibolkvadze commented on src/documentation/pages/components-wip/toolbar/_accessibility.vue
> +  AccessibilityComingSoon
`<AccessibilityComingSoon />`

2022-08-19 11:25 UTC, janibolkvadze commented on src/documentation/pages/components-wip/toolbar/_properties.vue
> +                  code true
Is this accurate default value?

2022-08-19 11:25 UTC, janibolkvadze commented on src/documentation/pages/components-wip/toolbar/index.vue
> +        Examples
`<Examples />`

2022-09-05 08:20 UTC, janibolkvadze approved these changes

2022-09-05 09:52 UTC, merged