[FSDE-25769] Test Algolia Search migration
CenturyLink/Chi pull request #451
Opened 2022-08-18 09:26 UTC by janibolkvadze

2022-08-18 09:28 UTC, janibolkvadze commented on src/website/assets/scripts/algoliaSearch.js
> +  debug: true
Temporary flag to test the migration.

2022-09-01 09:52 UTC, janibolkvadze commented on src/documentation/layouts/wide.vue
> +\<template lang="pug">
```suggestion
<template lang="pug">
```

2022-09-01 18:01 UTC, mattnickles requested changes

2022-09-01 18:01 UTC, mattnickles commented on src/website/assets/themes/brightspeed/_header.scss
> +          color: $text-input-placeholder-text-color;
```suggestion
        .DocSearch-Button {
          background: $color-background-white;
          border: 0.0625rem solid $text-input-border-color;
          border-radius: $border-radius-base;
          color: $text-input-placeholder-text-color;
          font-weight: $font-weight-normal;
```

2022-09-01 18:18 UTC, mattnickles approved these changes

2022-09-02 04:28 UTC, merged