[FSDE-27809] Remove conditional rendering of Chi vue component classes
CenturyLink/Chi pull request #471
Opened 2022-09-15 13:50 UTC by tjimenezLumen

2022-09-15 15:36 UTC, josecarlosgonzalezv requested changes
Why do you need to upload the `package-lock.json` from the root folder? Please check all unused classes in each file and solve the linting problems.

2022-09-15 15:36 UTC, josecarlosgonzalezv commented on src/chi-vue/src/components/data-table-filters/AdvancedFilters.tsx
>    GENERIC_SIZE_CLASSES,
Unused imported class
```suggestion
```

2022-09-15 15:36 UTC, josecarlosgonzalezv commented on src/chi-vue/src/components/data-table-filters/AdvancedFilters.tsx
>    PORTAL_CLASS,
Unused imported class
```suggestion
```

2022-09-16 16:17 UTC, janibolkvadze commented on src/chi-vue/src/components/data-table-filters/AdvancedFilters.tsx
> -    this._chiMajorVersion = detectMajorChiVersion();
This removes the lifecycle hook but the declaration of `_chiMajorVersion` is still there. Please check line 73.

2022-09-16 16:18 UTC, janibolkvadze commented on src/chi-vue/src/components/column-customization/ColumnCustomization.tsx
> -    this._chiMajorVersion = detectMajorChiVersion();
This removes the lifecycle hook but the declaration of `_chiMajorVersion` is still there. Please check line 34.

2022-09-16 16:20 UTC, janibolkvadze commented on src/chi-vue/src/components/data-table-filters/DataTableFilters.tsx
> -  beforeMount() {
Same here.

2022-09-16 16:20 UTC, janibolkvadze commented on src/chi-vue/src/components/data-table-filters/DataTableFilters.tsx
> -    this._chiMajorVersion = detectMajorChiVersion();
Same here.

2022-09-16 16:22 UTC, janibolkvadze commented on src/chi-vue/src/components/data-table-views/DataTableViews.tsx
> -    this._chiMajorVersion = detectMajorChiVersion();
Same here.

2022-09-16 16:27 UTC, janibolkvadze commented on src/chi-vue/src/components/data-table/DataTable.tsx
>    GENERIC_SIZE_CLASSES,
Aparently, classes.ts holds the same objects for the generic classes as `GENERIC_SIZES` & `GENERIC_SIZE_CLASSES`. We need remove `GENERIC_SIZES` and use `GENERIC_SIZE_CLASSES` in all the cases.

2022-09-16 16:28 UTC, janibolkvadze commented on src/chi-vue/src/components/data-table/DataTable.tsx
> -    this.detectScreenBreakpoint();
This will break the resize handler functionality and the responsiveness of the data table (hide, show column) will not work.

2022-09-16 16:30 UTC, janibolkvadze commented on src/chi-vue/src/components/search-input/SearchInput.tsx
> -    this._chiMajorVersion = detectMajorChiVersion();
Same here, line 30.

2022-09-16 17:19 UTC, janibolkvadze approved these changes

2022-09-16 17:19 UTC, josecarlosgonzalezv approved these changes

2022-09-16 17:20 UTC, jllr approved these changes

2022-09-16 17:24 UTC, merged