[FSDE-28315]Remove unused variables in Chi vue components
CenturyLink/Chi pull request #481
Opened 2022-10-05 12:21 UTC by tjimenezLumen

https://ctl.atlassian.net/browse/FSDE-28315

2022-10-05 15:48 UTC, josecarlosgonzalezv requested changes
In this pull request we must also delete all related `portal` variables, as we do not use them any more.


![image](https://user-images.githubusercontent.com/86958774/194104320-16f0f8b4-1e87-4eb1-84b3-be62d2a9926d.png)

2022-10-06 11:17 UTC, josecarlosgonzalezv requested changes
Drawer.tsx still have `@Prop() portal!: boolean;`

2022-10-06 11:17 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/tabs/tabs.tsx
>              >
```suggestion
            >
```

2022-10-07 09:34 UTC, josecarlosgonzalezv requested changes

2022-10-07 09:34 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/tabs/tabs.tsx
> -              this.seeMoreDropdown.hide();
Do not remove this line.

2022-10-07 10:33 UTC, josecarlosgonzalezv approved these changes

2022-10-14 09:54 UTC, jllr approved these changes

2022-10-14 11:55 UTC, merged