Implemented chi-tabs web component in chi documentation
CenturyLink/Chi pull request #490
Opened 2022-10-18 20:40 UTC by soujanreddy

2022-11-16 21:18 UTC, mattnickles reviewed
@jllr @josecarlosgonzalezv @soujanreddy Drop down tab items appear to be missing [a chevron icon](https://assets.ctl.io/chi/5.24.0/components/tabs/?theme=Lumen#tabbed-navigation-bar). Also it looks like we lost the ability to open drop down tab items with the keyboard - need this to pass accessibility.

2022-11-16 21:38 UTC, mattnickles reviewed
@jllr @josecarlosgonzalezv @soujanreddy In the previous implementation, we preserved the -active class on the parent tab item li if one of its children was set to active. The parent no longer renders with an -active class which is causing the text color to display as black instead of blue.

![image](https://user-images.githubusercontent.com/130654/202299886-ea5b4945-8f90-4c48-b4f0-c71c8b6c75b8.png)

2023-01-18 09:44 UTC, josecarlosgonzalezv requested changes

2023-01-18 09:44 UTC, josecarlosgonzalezv commented on src/website/views/components/tabs/_examples.pug
> +        <chi-tabs active-tab="tab-a" id="example__tabbednavigation_flat" sliding-border></chi-tabs>
```suggestion
        <chi-tabs active-tab="tab-a" id="example__tabbed_navigation_flat" sliding-border></chi-tabs>
```

2023-01-18 09:44 UTC, josecarlosgonzalezv commented on src/website/views/components/tabs/_examples.pug
> +          const tabbedNavigationFlatElement = document.querySelector('#example__tabbednavigation_flat');
```suggestion
          const tabbedNavigationFlatElement = document.querySelector('#example__tabbed_navigation_flat');
```

2023-01-18 09:44 UTC, josecarlosgonzalezv commented on src/website/views/components/tabs/_examples.pug
> +          tabbedNavigationFlatElement.tabs = [
```suggestion
          
          tabbedNavigationFlatElement.tabs = [
```

2023-01-18 09:44 UTC, josecarlosgonzalezv commented on src/website/views/components/tabs/_examples.pug
> +          const tabbedNavigationSolidElement = document.querySelector('#example__tabbednavigation_solid');
```suggestion
          const tabbedNavigationSolidElement = document.querySelector('#example__tabbed_navigation_solid');
```

2023-01-25 11:33 UTC, josecarlosgonzalezv requested changes

2023-01-25 11:33 UTC, josecarlosgonzalezv commented on src/website/views/components/tabs/_examples.pug
> +      chi-tabs(active-tab='tab-a' id='example_tabbed_navigation_flat' sliding-border)
```suggestion
      chi-tabs(active-tab='tab-a' id='example__tabbed_navigation_flat' sliding-border)
```

2023-01-25 11:33 UTC, josecarlosgonzalezv commented on src/website/views/components/tabs/_examples.pug
> +      chi-tabs(active-tab='tab-aa' id='example_tabbed_navigation_solid' solid sliding-border)
```suggestion
      chi-tabs(active-tab='tab-aa' id='example__tabbed_navigation_solid' solid sliding-border)
```

2023-01-25 15:59 UTC, josecarlosgonzalezv approved these changes

2023-01-27 10:58 UTC, josecarlosgonzalezv requested changes

2023-01-27 10:58 UTC, josecarlosgonzalezv commented on src/website/views/components/tabs/_examples.pug
> +                      id: 'tab-h-1'
```suggestion
                      id: 'tab-h-2-1'
```

2023-01-27 10:58 UTC, josecarlosgonzalezv commented on src/website/views/components/tabs/_examples.pug
> +                          id: 'tab-h-3-1'
```suggestion
                          id: 'tab-h-2-3-1'
```

2023-01-27 10:58 UTC, josecarlosgonzalezv commented on src/website/views/components/tabs/_examples.pug
> +                          id: 'tab-h-3-2'
```suggestion
                          id: 'tab-h-2-3-2'
```

2023-01-27 10:58 UTC, josecarlosgonzalezv commented on src/website/views/components/tabs/_examples.pug
> +                          id: 'tab-h-3-3'
```suggestion
                          id: 'tab-h-2-3-3'
```

2023-01-27 10:58 UTC, josecarlosgonzalezv commented on src/website/views/components/tabs/_examples.pug
> +                      id: 'tab-h-4'
```suggestion
                      id: 'tab-h-2-4'
```

2023-01-27 10:58 UTC, josecarlosgonzalezv commented on src/website/views/components/tabs/_examples.pug
> +                      id: 'tab-f-1'
```suggestion
                      id: 'tab-f-2-1'
```

2023-01-27 10:58 UTC, josecarlosgonzalezv commented on src/website/views/components/tabs/_examples.pug
> +                      id: 'tab-f-2'
```suggestion
                      id: 'tab-f-2-2'
```

2023-01-27 10:58 UTC, josecarlosgonzalezv commented on src/website/views/components/tabs/_examples.pug
> +                      id: 'tab-f-3',
```suggestion
                      id: 'tab-f-2-3',
```

2023-01-27 10:58 UTC, josecarlosgonzalezv commented on src/website/views/components/tabs/_examples.pug
> +                          id: 'tab-f-3-1'
```suggestion
                          id: 'tab-f-2-3-1'
```

2023-01-27 10:58 UTC, josecarlosgonzalezv commented on src/website/views/components/tabs/_examples.pug
> +                          id: 'tab-f-3-2'
```suggestion
                          id: 'tab-f-2-3-2'
```

2023-01-27 10:58 UTC, josecarlosgonzalezv commented on src/website/views/components/tabs/_examples.pug
> +                          id: 'tab-f-3-3'
```suggestion
                          id: 'tab-f-2-3-3'
```

2023-01-27 10:58 UTC, josecarlosgonzalezv commented on src/website/views/components/tabs/_examples.pug
> +                      id: 'tab-f-4'
```suggestion
                      id: 'tab-f-2-4'
```

2023-01-27 15:30 UTC, jllr requested changes

2023-01-27 15:30 UTC, jllr commented on src/website/views/components/tabs/_examples.pug
> +                      id: 'tab-h-2'
```suggestion
                      id: 'tab-h-2-2'
```

2023-01-27 15:30 UTC, jllr commented on src/website/views/components/tabs/_examples.pug
> +                      id: 'tab-h-3',
```suggestion
                      id: 'tab-h-2-3',
```

2023-01-27 16:38 UTC, jllr approved these changes

2023-01-27 16:44 UTC, josecarlosgonzalezv approved these changes

2023-01-30 08:41 UTC, merged