[FSDE-29974]Add support for autoplay in carrousel component
CenturyLink/Chi pull request #526
Opened 2022-12-02 16:06 UTC by tjimenezLumen

[FSDE-29974]Add support for autoplay in carrousel component

2022-12-02 16:38 UTC, josecarlosgonzalezv requested changes

2022-12-02 16:38 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/carousel/carousel.tsx
> -
Why remove this space?

2022-12-02 16:38 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/carousel/carousel.tsx
> +   * To render Carousel with pagination indicators
Change the descriptions and do a `chi build` to generate the new properties in the documentation.

```suggestion
   * To set the autoplay for the carousel
```

2022-12-02 16:38 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/carousel/carousel.tsx
> +   * To render Carousel with pagination indicators
```suggestion
   * To set the delay for the autoplay
```

2022-12-02 16:38 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/carousel/carousel.tsx
> +  @Prop() delay: number;
Gives a default delay in case the user does not set this property.

```suggestion
  @Prop() delay: number = 3000;
```

2022-12-02 16:38 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/carousel/carousel.tsx
> +        }
```suggestion
     if (this.view === this.numberOfViews - 1) {
          this.view = -1;
        }

        this.nextView();
```

2022-12-20 18:18 UTC, SergioQCL approved these changes

2022-12-21 09:39 UTC, josecarlosgonzalezv approved these changes

2022-12-30 11:04 UTC, jllr approved these changes

2022-12-30 11:07 UTC, merged