[FSDE-30490] Add support for selecting all items on data table
CenturyLink/Chi pull request #562
Opened 2023-01-26 12:48 UTC by josecarlosgonzalezv

https://ctl.atlassian.net/browse/FSDE-30490

2023-01-26 16:04 UTC, SergioQCL approved these changes

2023-01-26 16:34 UTC, mattnickles commented on src/chi-vue/src/components/data-table/DataTable.tsx
> +    const deselectAllSelectionMessage = 'Deselect none';
Sorry there was a typo in the design prototype. This should be 'Deselect all'
```suggestion
    const deselectAllSelectionMessage = 'Deselect all';
```

2023-01-27 15:57 UTC, jllr requested changes

2023-01-27 15:57 UTC, jllr commented on src/chi-vue/src/components/data-table/data-table.scss
> +            left: 40px;
```suggestion
            left: 2.5rem;
            position: absolute;
```

2023-01-27 15:57 UTC, jllr commented on src/chi/components/data-table/data-table.scss
> +                left: 40px;
```suggestion
                left: 2.5rem;
                position: absolute;
```

2023-02-03 00:15 UTC, mattnickles reviewed
@josecarlosgonzalezv @jllr Let's change "Items selected" to "Items Selected"  so the casing is consistent with the title casing used in the "Show Selected Only" checkbox, table headers, etc.

2023-02-03 00:23 UTC, mattnickles reviewed
@josecarlosgonzalezv @jllr Do you want to fix the vertical alignment of the items selected label in this PR or separate? We just need to add `align-items: center;` to line 69 of bulk-actions.scss

2023-02-03 17:26 UTC, mattnickles approved these changes

2023-02-03 18:14 UTC, merged