[FSDE-18246] Migrate Expansion panel component to new Vue Documentation
CenturyLink/Chi pull request #605
Opened 2023-03-06 20:16 UTC by lumdmtr

2023-03-13 11:33 UTC, krzysztofdrozdowskilumen commented on src/documentation/.gitignore
> +.npmrc
Great idea! I think we should consider including that in other .gitignore files 👏

2023-05-08 15:18 UTC, josecarlosgonzalezv commented on src/documentation/pages/components-wip/expansion-panel/examples/_bordered.vue
> +      .p--text(class="chi-tab__description")
```suggestion
      .p--text.chi-tab__description
```

2023-05-08 15:21 UTC, josecarlosgonzalezv commented on src/documentation/pages/components-wip/expansion-panel/examples/_no-step.vue
> +      .p--text(class="chi-tab__description")
Same here

2023-05-29 13:15 UTC, josecarlosgonzalezv requested changes

2023-05-29 13:15 UTC, josecarlosgonzalezv commented on src/documentation/pages/components-wip/expansion-panel/examples/_state_icon.vue
> +  <ComponentExample title="State Icon" id="stateIcon" :tabs="exampleTabs" padding="-p--3 -p-lg--6" additionalClasses="-bg--grey-10">
```suggestion
  <ComponentExample title="State Icon" id="state-icon" :tabs="exampleTabs" padding="-p--3 -p-lg--6" additionalClasses="-bg--grey-10">
```

2023-05-30 09:08 UTC, josecarlosgonzalezv approved these changes

2023-05-30 09:32 UTC, jllr approved these changes

2023-05-30 09:43 UTC, merged