[FSDE-30808] Change See more... tabs to More
CenturyLink/Chi pull request #613
Opened 2023-03-13 10:13 UTC by krzysztofdrozdowskilumen

https://ctl.atlassian.net/browse/FSDE-30808

2023-03-13 15:56 UTC, josecarlosgonzalezv approved these changes

2023-03-13 17:53 UTC, mattnickles requested changes

2023-03-13 17:53 UTC, mattnickles commented on src/custom-elements/src/constants/constants.ts
> +export const TABS_SEE_MORE_DEFAULT_MESSAGE = 'More...';
Let's change 'More...' to 'More' for consistency with the portal style guide.

```suggestion
export const TABS_SEE_MORE_DEFAULT_MESSAGE = 'More';
```

2023-03-13 17:53 UTC, mattnickles commented on src/chi/components/tabs/tabs.scss
> +@mixin chevron-icon {
Would suggest renaming 'chevron-icon' to 'dropdown-icon' as it may not be a chevron in all themes.

2023-03-13 17:53 UTC, mattnickles commented on src/chi/components/tabs/tabs.scss
> +  font-family: chi;
Let's use the `$font-family-icon` variable here. Using a variable will also resolve an [error in Sonarqube ](https://rules.sonarsource.com/css/RSPEC-4649)which expects at least one generic font family in the value.

```suggestion
  font-family: $font-family-icon;
```

2023-03-14 16:40 UTC, mattnickles approved these changes

2023-03-14 17:54 UTC, merged