[FSDE-30809] Include tabbed navigation bar in Lumen Enterprise Portal theme
CenturyLink/Chi pull request #614
Opened 2023-03-16 08:23 UTC by kosgor

https://ctl.atlassian.net/jira/software/c/projects/FSDE/boards/4081?modal=detail&selectedIssue=FSDE-30809&assignee=63f3b2d5526117e1514b85f6&assignee=63ef4f14c5061c632c0e2259

2023-03-16 10:11 UTC, jllr requested changes

2023-03-16 10:11 UTC, jllr commented on src/website/views/components/tabs/_examples.pug
> +div
```suggestion
```

2023-03-16 10:11 UTC, jllr commented on src/website/views/components/tabs/_examples.pug
> +div
@kosgor, div tag is not neccesary in pug files. Code asociated with Tabbed navigation bar must be indented properly. You can take a look at close icon button in button doc page to see how it is done.  
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/17043903/225584996-b513b659-f0b4-4ca8-b9b3-eeb4f2a37d2e.png)

2023-03-17 09:54 UTC, krzysztofdrozdowskilumen approved these changes
Well done 🎉

2023-03-28 09:40 UTC, closed without merging