[FSDE-30880] Implement datatable radio selection component to be used in Lumen Enterprise Portal
CenturyLink/Chi pull request #621
Opened 2023-03-21 13:33 UTC by pedrotaglialatela-lumen

https://ctl.atlassian.net/browse/FSDE-30880

- Created a new component for radio selection in the Portal's directory base
- Component implemented in examples

2023-03-21 16:20 UTC, jllr requested changes
Please review the configs and make sure that everything is rendering properly for Lumen Enterprise Portal theme.

2023-03-21 16:20 UTC, jllr commented on src/website/views/components/data-table/examples/portal/_radio-selection.pug
> +            portal: false,
```suggestion
            portal: true,
```

2023-03-21 16:20 UTC, jllr commented on src/website/views/components/data-table/examples/portal/_radio-selection.pug
> +            striped: false,
```suggestion
            striped: true,
```

2023-03-22 09:20 UTC, jllr approved these changes

2023-03-22 09:34 UTC, josecarlosgonzalezv approved these changes

2023-03-22 09:37 UTC, merged