[FSDE-30888] Add support for sizes in Tabs web component
CenturyLink/Chi pull request #622
Opened 2023-03-21 13:49 UTC by kosgor

https://ctl.atlassian.net/jira/software/c/projects/FSDE/boards/4081?modal=detail&selectedIssue=FSDE-30888

2023-03-23 09:40 UTC, jllr requested changes

2023-03-23 17:45 UTC, josecarlosgonzalezv requested changes

2023-03-23 17:45 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/tabs/tabs.tsx
> +    if (newValue && !['', 'xs', 'sm', 'md', 'lg', 'xl'].includes(newValue)) {
```suggestion
    if (newValue && !TABS_SIZES.includes(newValue)) {
```

2023-03-23 17:45 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/tabs/tabs.tsx
> +  @Prop({ reflect: true }) size: string;
```suggestion
  @Prop({ reflect: true }) size: string = 'md';
```

2023-03-23 17:45 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/tabs/tabs.tsx
> +  private marginLeftValue: number = this.size === 'lg' ? 32 : 24;
```suggestion
  private marginLeft: number = this.size === 'lg' ? MARGIN_LEFT_LG : MARGIN_LEFT_BASE;
```

2023-03-24 16:39 UTC, josecarlosgonzalezv requested changes

2023-03-24 16:39 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/tabs/tabs.tsx
> +   *  to set tab size { xs, sm, md, lg, xl }.
```suggestion
   *  To set tab size { xs, sm, md, lg, xl }.
```

2023-03-24 16:40 UTC, josecarlosgonzalezv requested changes

2023-03-24 16:40 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/tabs/tabs.tsx
> +  @Prop({ reflect: true }) size ?: TabsSizes = 'md';
```suggestion
  @Prop({ reflect: true }) size?: TabsSizes = 'md';
```

2023-03-27 11:12 UTC, jllr approved these changes

2023-03-27 11:14 UTC, merged