[FSDE-30898] Prevent opening accesibility when clicking on Grid, Foundations page
CenturyLink/Chi pull request #626
Opened 2023-03-23 08:05 UTC by krzysztofdrozdowskilumen

https://ctl.atlassian.net/browse/FSDE-30898

2023-03-27 11:12 UTC, krzysztofdrozdowskilumen commented
Hey!
I moved the sidenav script to a separate file. It's still loaded in the sidenav.pug file because in the default file it causes a bug with the arrow animation 🙂

2023-03-29 12:18 UTC, josecarlosgonzalezv requested changes

2023-03-29 12:18 UTC, josecarlosgonzalezv commented on src/website/assets/scripts/sidenav.js
> +})();
```suggestion
var accordions = document.querySelectorAll('.chi-accordion');

accordions.forEach(accordion => {
  var accordionItem = accordion.querySelector('.chi-accordion__item');
  var hasActiveChild = !!accordion.querySelector('.-active');

  if (hasActiveChild) {
    accordionItem.classList.add('-expanded');
  }
});

```

2023-03-30 09:10 UTC, jllr approved these changes

2023-03-30 09:34 UTC, merged