[FSDE-31007] add search-input+dropdown example
CenturyLink/Chi pull request #642
Opened 2023-04-04 15:48 UTC by lumdmtr

2023-04-05 11:13 UTC, jllr requested changes

2023-04-05 11:13 UTC, jllr commented on src/website/views/components/forms/search-input/_examples.pug
> +        <chi-search-input></chi-search-input>
```suggestion
        <chi-search-input id="with-dropdown"></chi-search-input>
```

2023-04-05 11:13 UTC, jllr commented on src/website/views/components/forms/search-input/_examples.pug
> +
```suggestion


```

2023-04-05 11:13 UTC, jllr commented on src/website/views/components/forms/search-input/_examples.pug
> +
@lumdmtr I have removed in codepen file and it worked fine. I think is not neccessary

2023-04-05 11:18 UTC, josecarlosgonzalezv commented on src/website/views/components/forms/search-input/_examples.pug
> +          document.getElementById("dropdown").show(); // toggle()
```suggestion
          dropdown.show();
```

2023-04-05 11:19 UTC, josecarlosgonzalezv commented on src/website/views/components/forms/search-input/_examples.pug
> +        const input = document.getElementById("with-dropdown");
Add the `chiClean` event to hide the dropdown.

```
input.addEventListener("chiClean", () => {
  dropdown.hide();
});
```

2023-04-05 11:21 UTC, josecarlosgonzalezv commented on src/website/views/components/forms/search-input/_examples.pug
> +
Make the changes requested for the web components code snippet here as well.

2023-04-05 11:21 UTC, josecarlosgonzalezv commented on src/website/views/components/forms/search-input/_examples.pug
> +      <div class="chi">
Review the HTML code snippet and make sure that it works.

2023-04-05 11:23 UTC, josecarlosgonzalezv commented on src/website/views/components/forms/search-input/_examples.pug
> +    ul.chi-tabs#example-with-dropdown(role="tablist")
Include a Vue example

2023-04-10 15:57 UTC, jllr requested changes

2023-04-10 15:57 UTC, jllr commented on src/website/views/components/forms/search-input/_examples.pug
> +      <div class="chi chi-form__item">
```suggestion
      <div class="chi-form__item">
```

2023-04-11 10:05 UTC, josecarlosgonzalezv approved these changes

2023-04-11 11:49 UTC, josecarlosgonzalezv requested changes

2023-04-11 11:49 UTC, josecarlosgonzalezv commented on src/website/views/components/forms/search-input/_examples.pug
> +          chi-dropdown#example__dropdown(position='bottom')
Include here and in the code snippets.

```suggestion
          chi-dropdown#example__dropdown(prevent-auto-hide position='bottom')
```

2023-04-11 11:49 UTC, josecarlosgonzalezv commented on src/website/views/components/forms/search-input/_examples.pug
> +      });
```suggestion
      input.addEventListener("chiFocus", () => {
        dropdown.show();
      });

      input.addEventListener("chiBlur", () => {
        dropdown.hide();
      });
```

2023-04-11 13:13 UTC, josecarlosgonzalezv approved these changes

2023-04-11 14:19 UTC, jllr approved these changes

2023-04-11 14:21 UTC, merged