[FSDE-31079] Alert component - Add mutable attribute to dismissible button
CenturyLink/Chi pull request #650
Opened 2023-04-13 00:22 UTC by pedrotaglialatela-lumen

2023-04-26 13:13 UTC, josecarlosgonzalezv requested changes

2023-04-26 13:13 UTC, josecarlosgonzalezv commented on cypress/integration/chi-custom-elements/alert.spec.js
> +    it('dismissible alert banner should be removed after clicking the X button', () => {
```suggestion
    it('Should remove alert banner after clicking the X button', () => {
```

2023-04-26 13:13 UTC, josecarlosgonzalezv commented on src/website/views/components/alert/_examples.pug
> +      chi-alert.-m--2(color='warning', icon='warning', title="Warning", closable, mutable)
```suggestion
      chi-alert.-m--2(color='warning', icon='warning', title="Warning", closable)
```

2023-04-26 13:13 UTC, josecarlosgonzalezv commented on test/chi/custom-elements/alert-banner.pug
> +        chi-alert.-m--2(class=type, icon=val, type="banner" closable, mutable, size=`${size === 'default' ? '' : size}`, data-cy=`alert-banner-dismissible-${type}-${size}`)
```suggestion
        chi-alert.-m--2(class=type, icon=val, type="banner" closable, size=`${size === 'default' ? '' : size}`, data-cy=`alert-banner-dismissible-${type}-${size}`)
```

2023-04-27 08:19 UTC, josecarlosgonzalezv approved these changes

2023-04-27 08:40 UTC, jllr approved these changes

2023-04-27 08:40 UTC, merged