Fsde 18263 shadow page
CenturyLink/Chi pull request #690
Opened 2023-05-16 13:20 UTC by ismael-teixeira

https://ctl.atlassian.net/jira/software/c/projects/FSDE/boards/4081?modal=detail&selectedIssue=FSDE-18263&assignee=712020%3Acd2bf38b-256e-496d-ba19-2aa8cc787e3d

2023-07-06 14:36 UTC, josecarlosgonzalezv requested changes

2023-07-06 14:36 UTC, josecarlosgonzalezv commented on src/documentation/pages/utilities-wip/shadow/examples/_sass.vue
> +    <pre class="language-html -mb--4" slot="code-htmlblueprint">
```suggestion
    <pre class="language-css" slot="code-htmlblueprint">
```

2023-07-06 14:36 UTC, josecarlosgonzalezv commented on src/documentation/pages/utilities-wip/shadow/examples/_sass.vue
> +  div
```suggestion
  .-mb--4
```

2023-07-06 14:46 UTC, josecarlosgonzalezv approved these changes

2023-07-07 08:53 UTC, jllr approved these changes

2023-07-07 08:55 UTC, merged