[FSDE-31351] Add functional example of closable alert in doc
CenturyLink/Chi pull request #699
Opened 2023-05-30 13:41 UTC by mtadejalumen

https://ctl.atlassian.net/browse/FSDE-31351

2023-06-06 14:31 UTC, jllr requested changes
@mtadejalumen please change the alert in the example to warning with title. 
Also update code snippets to reflect the changes.
![Screen Shot 2023-06-06 at 4 27 19 PM](https://github.com/CenturyLink/Chi/assets/17043903/1b177f43-a0a5-42a8-a3f5-ab239ba123c8)

2023-06-06 14:31 UTC, jllr commented on src/website/views/components/alert/_examples.pug
> +    .chi-tab__description
```suggestion
```

2023-06-06 14:31 UTC, jllr commented on src/website/views/components/alert/_examples.pug
> +    chi-alert#interactive-alert(icon='circle-info', closable, mutable).-m--2
```suggestion
    chi-alert.-mt--2#interactive-alert(title='Warning', color='warning', icon='warning', closable)
```

2023-06-06 14:31 UTC, jllr commented on src/website/views/components/alert/_examples.pug
> +      | This is a base alert
```suggestion
      | This is a closable warning alert
```

2023-06-06 14:31 UTC, jllr commented on src/website/views/components/alert/_examples.pug
> +h4 Interactive
```suggestion
h4 Closable alert interaction
```

2023-06-06 14:32 UTC, josecarlosgonzalezv requested changes

2023-06-06 14:32 UTC, josecarlosgonzalezv commented on src/website/views/components/alert/_examples.pug
> +    setupInteractiveAlert();
I would change a little bit the `script` part:

![image](https://github.com/CenturyLink/Chi/assets/86958774/54e043ed-c792-4b08-b705-d33d121815bb)

2023-06-07 13:26 UTC, jllr requested changes
@mtadejalumen code snippet should include the button that trigger the action. Similar as it is in the [modal](https://lib.lumen.com/chi/5.33.0/components/modal/?theme=Portal#base), [drawer](https://lib.lumen.com/chi/5.33.0/components/modal/?theme=Portal#base)

2023-06-07 13:26 UTC, jllr commented on src/website/views/components/alert/_examples.pug
> +    chi-button#alert-trigger-button(variant='outline')
```suggestion
    chi-button#alert-trigger-button(color='primary')
```

2023-06-13 07:12 UTC, jllr requested changes

2023-06-13 07:12 UTC, jllr commented on src/website/views/components/alert/_examples.pug
> +        </chi-alert>
@mtadejalumen code snippets are not refelecting warning alert in web component and html blueprint. Please update

2023-06-13 07:12 UTC, jllr commented on src/website/views/components/alert/_examples.pug
> +      </script>
@mtadejalumen This logic is only needed for the example that we have in documentation. For developers the only needed logic is one button that triggers an alert. Please remove unnecessary code.

2023-06-21 09:14 UTC, jllr approved these changes

2023-06-21 09:16 UTC, josecarlosgonzalezv approved these changes

2023-06-21 09:21 UTC, merged