[FSDE-674] Add support of column customization submodule to toolbar section
CenturyLink/Chi pull request #70
Opened 2021-06-08 21:10 UTC by janibolkvadze

https://user-images.githubusercontent.com/25136131/121257900-89669c00-c8ae-11eb-8ea7-762190b92d12.mov

https://ctl.atlassian.net/browse/FSDE-674

2021-06-08 21:11 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-70/1/. :x:

2021-06-09 09:57 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-70/2/. :white_check_mark:

2021-06-09 09:57 UTC, SCMAUTO commented
You can check this PRs instance in https://f5e1bec7ee8b2905983c5bcc0fbd95d85e470080-chi-pr.enterprise.ctl.io

2021-06-09 18:17 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-70/3/. :white_check_mark:

2021-06-09 18:17 UTC, SCMAUTO commented
You can check this PRs instance in https://cff32b6ac95869e13769f8a91216256b55fbc56b-chi-pr.enterprise.ctl.io

2021-06-10 15:32 UTC, dani-cl-madrid requested changes

2021-06-10 15:32 UTC, dani-cl-madrid commented on src/chi-vue/src/components/column-customization/ColumnCustomizationModalContent.tsx
> +    Array.from((this._selectedColumnsComponent?.$refs.select as HTMLSelectElement).selectedOptions).forEach(
Again, selected options. Please look for any other case.

2021-06-11 20:01 UTC, janibolkvadze commented on src/chi-vue/src/components/column-customization/utils.ts
> +  }
Good catch. Initially, this was part of the moveDown functionality but then I changed the approach, this is leftover code.
I will remove it. 🤝

2021-06-11 21:49 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-70/4/. :white_check_mark:

2021-06-11 21:50 UTC, SCMAUTO commented
You can check this PRs instance in https://e5ac06a738e2cc9badee634fa7f138ef6c0bcbaf-chi-pr.enterprise.ctl.io

2021-06-14 09:28 UTC, SergioQCL approved these changes
ACK

2021-06-14 13:47 UTC, dani-cl-madrid approved these changes
ACK

2021-06-14 16:49 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-70/5/. :white_check_mark:

2021-06-14 16:49 UTC, SCMAUTO commented
You can check this PRs instance in https://6d6922a538ae59df85ad87bd0694bff0b185099a-chi-pr.enterprise.ctl.io

2021-06-15 14:07 UTC, jllr approved these changes

2021-06-15 14:07 UTC, merged