[FSDE-31409] chi add support for additional messaging below text input components
CenturyLink/Chi pull request #726
Opened 2023-06-23 01:27 UTC by pedrotaglialatela-lumen

https://ctl.atlassian.net/browse/FSDE-31389

2023-07-04 08:36 UTC, josecarlosgonzalezv requested changes

2023-07-04 11:41 UTC, jllr commented on src/custom-elements/src/components/helper-message/helper-message.scss
> +:host(chi-label) {
@pedrotaglialatela-lumen if the component is helper-message, for what is needed chi-label?

2023-07-05 13:19 UTC, josecarlosgonzalezv requested changes

2023-07-05 13:19 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/helper-message/helper-message.tsx
> +  tag: 'helper-message',
```suggestion
  tag: 'chi-helper-message',
```

2023-07-05 13:19 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/text-input/text-input.tsx
> +    const helperMessage = this.helperMessage && <helper-message state={this.state}>{this.helperMessage}</helper-message>;
```suggestion
    const helperMessage = this.helperMessage && <chi-helper-message state={this.state}>{this.helperMessage}</helper-message>;
```

2023-07-05 13:19 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/helper-message/helper-message.scss
> +:host(helper-message) {
```suggestion
:host(chi-helper-message) {
```

2023-07-06 00:02 UTC, pedrotaglialatela-lumen commented on src/custom-elements/src/components/helper-message/helper-message.scss
> +:host(helper-message) {
Done!!

2023-07-06 00:02 UTC, pedrotaglialatela-lumen commented on src/custom-elements/src/components/text-input/text-input.tsx
> +    const helperMessage = this.helperMessage && <helper-message state={this.state}>{this.helperMessage}</helper-message>;
Done!!

2023-07-06 00:03 UTC, pedrotaglialatela-lumen commented on src/custom-elements/src/components/helper-message/helper-message.tsx
> +  tag: 'helper-message',
Done. Good catch. Thank you, Jose! 👍

2023-07-06 10:47 UTC, josecarlosgonzalezv approved these changes

2023-07-06 14:17 UTC, jllr approved these changes

2023-07-06 14:17 UTC, merged