[FSDE-31132] Add state support to data table vue component
CenturyLink/Chi pull request #747
Opened 2023-07-12 01:03 UTC by pedrotaglialatela-lumen

2023-10-10 15:18 UTC, josecarlosgonzalezv requested changes

2023-10-10 15:18 UTC, josecarlosgonzalezv commented on src/chi-vue/src/components/data-table/DataTable.tsx
> +      if (shouldExpand || hasState) {
```suggestion
      const shouldExpand = rowObject.expanded && !this.accordionsExpanded.includes(rowObject.rowId);
      
      if (shouldExpand || hasState) {
```

2023-10-10 15:18 UTC, josecarlosgonzalezv commented on src/chi-vue/src/constants/types.ts
> +  state?: string;
I would have something more restrictive like:

`export const DATA_TABLE_ROW_STATES = ['success', 'warning', 'danger', 'info'] as const;`
`export type DataTableRowStates = typeof DATA_TABLE_ROW_STATES[number];`

```suggestion
  state?: DataTableRowStates;
```

2023-10-11 08:08 UTC, josecarlosgonzalezv approved these changes

2023-10-11 08:27 UTC, jllr approved these changes

2023-10-11 08:28 UTC, merged