[FSDE-31608] Implement some functional use case tests for helper message in text input component
CenturyLink/Chi pull request #761
Opened 2023-07-27 14:50 UTC by pedrotaglialatela-lumen

https://ctl.atlassian.net/browse/FSDE-31608

2023-07-28 10:19 UTC, josecarlosgonzalezv requested changes

2023-07-28 10:19 UTC, josecarlosgonzalezv commented on cypress/integration/chi-custom-elements/text-input.spec.js
> +  chi_text_input: 'chi-text-input',
Uppercase here and in every class.

```suggestion
  CHI_TEXT_INPUT: 'chi-text-input',
```

2023-07-28 10:19 UTC, josecarlosgonzalezv commented on cypress/integration/chi-custom-elements/text-input.spec.js
> +      cy.get('.test-helper-message-md')
Can we create a variable for this class and reuse it?

```suggestion
      cy.get(HELPER_MESSAGE_MD)
```

2023-08-02 09:47 UTC, josecarlosgonzalezv approved these changes

2023-08-02 10:32 UTC, merged

2023-08-02 10:33 UTC, SergioQCL approved these changes