[DPEDE-363] Migrate utilities sizing to new Vue documentation
CenturyLink/Chi pull request #789
Opened 2023-08-30 09:06 UTC by kosgor

2023-10-02 10:09 UTC, josecarlosgonzalezv requested changes

2023-10-02 10:09 UTC, josecarlosgonzalezv commented on src/documentation/pages/utilities-wip/sizing/examples/height.vue
> +<template lang="pug">
Rename to _height.vue

2023-10-02 10:09 UTC, josecarlosgonzalezv commented on src/documentation/pages/utilities-wip/sizing/examples/maximum-width-height.vue
> +<template lang="pug">
Rename to _maximum-width-height.vue

2023-10-02 10:09 UTC, josecarlosgonzalezv commented on src/documentation/pages/utilities-wip/sizing/examples/width.vue
> +<template lang="pug">
Rename to _width.vue

2023-10-02 10:09 UTC, josecarlosgonzalezv commented on src/documentation/pages/utilities-wip/sizing/index.vue
> +      title: 'Sizing - Color'
```suggestion
      title: 'Chi - Sizing'
```

2023-10-02 10:16 UTC, jllr approved these changes

2023-10-04 08:35 UTC, josecarlosgonzalezv approved these changes

2023-10-04 11:41 UTC, jllr approved these changes

2023-10-04 11:43 UTC, merged