[FSDE-279] Add interactive documentation examples of Chi Vue data table
CenturyLink/Chi pull request #79
Opened 2021-06-21 12:35 UTC by janibolkvadze

2021-06-21 13:37 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-79/1/. :white_check_mark:

2021-06-21 13:37 UTC, SCMAUTO commented
You can check this PRs instance in https://f6091d06c830f59a1c547a57e9f71a624fd34991-chi-pr.enterprise.ctl.io

2021-06-21 19:51 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-79/2/. :white_check_mark:

2021-06-21 19:51 UTC, SCMAUTO commented
You can check this PRs instance in https://25288b1b435dcf3352512f73a6ca644ed32ec132-chi-pr.enterprise.ctl.io

2021-06-22 10:36 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-79/3/. :white_check_mark:

2021-06-22 10:36 UTC, SCMAUTO commented
You can check this PRs instance in https://2cca868fe060f4c3278881131cd1bc80328c861a-chi-pr.enterprise.ctl.io

2021-06-22 18:47 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-79/4/. :white_check_mark:

2021-06-22 18:47 UTC, SCMAUTO commented
You can check this PRs instance in https://f83f8c17f75ca7acabac462f893ace28a4911045-chi-pr.enterprise.ctl.io

2021-06-29 08:18 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-79/5/. :x:

2021-06-29 10:58 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-79/6/. :white_check_mark:

2021-06-29 10:58 UTC, SCMAUTO commented
You can check this PRs instance in https://c2a506d193afa297609a6916db1eda92809d2c9c-chi-pr.enterprise.ctl.io

2021-06-29 18:03 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-79/7/. :white_check_mark:

2021-06-29 18:03 UTC, SCMAUTO commented
You can check this PRs instance in https://f097370cb5d7072a05635e83b583e9397f1c92cc-chi-pr.enterprise.ctl.io

2021-07-01 06:29 UTC, jllr requested changes
@janibolkvadze Portal examples row height should be 56px as per brand guidelines. Could you change it?

2021-07-01 06:29 UTC, jllr commented on src/website/views/components/data-table/examples/base/_sorting-ascending.pug
> +            direction: 'ascending',
@janibolkvadze please indent these 2 lines.

2021-07-01 06:29 UTC, jllr commented on src/website/views/components/data-table/examples/portal/_complex.pug
> +    :code(lang="html")
@janibolkvadze I would suggest removing html blueprint as it doesn't match with the Vue code example

2021-07-02 11:45 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-79/8/. :x:

2021-07-02 13:26 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-79/9/. :white_check_mark:

2021-07-02 13:26 UTC, SCMAUTO commented
You can check this PRs instance in https://d1ed7a144303d5c348fce6c1009b0f7223b5b3cf-chi-pr.enterprise.ctl.io

2021-07-20 21:17 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-79/10/. :white_check_mark:

2021-07-20 21:17 UTC, SCMAUTO commented
You can check this PRs instance in https://a309525273de414d9d1ef3bbcd79100c7bd11f0d-chi-pr.enterprise.ctl.io

2021-07-20 21:38 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-79/11/. :white_check_mark:

2021-07-20 21:38 UTC, SCMAUTO commented
You can check this PRs instance in https://7263244d348ff90086f7e3313372b79914d8898d-chi-pr.enterprise.ctl.io

2021-07-22 15:21 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-79/12/. :x:

2021-07-22 15:44 UTC, jllr approved these changes

2021-07-22 15:48 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-79/13/. :x:

2021-07-22 16:12 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-79/14/. :white_check_mark:

2021-07-22 16:12 UTC, SCMAUTO commented
You can check this PRs instance in https://256af5c76caa6a58c55d2b647a25d1a24da9668d-chi-pr.enterprise.ctl.io

2021-07-22 16:20 UTC, aryaroudi approved these changes

2021-07-22 16:21 UTC, merged