[DPEDE-671] Added spinner attribute to alert component
CenturyLink/Chi pull request #835
Opened 2023-10-09 11:21 UTC by wojciechwlodarczyklumen

https://ctl.atlassian.net/browse/DPEDE-671

2023-10-11 13:14 UTC, josecarlosgonzalezv approved these changes

2023-10-11 13:40 UTC, jllr approved these changes

2023-10-11 14:30 UTC, jllr requested changes

2023-10-11 14:30 UTC, jllr commented on src/website/views/components/alert/_examples.pug
> +    chi-alert(icon='circle-info', spinner).-m--2
```suggestion
    chi-alert(spinner).-m--2
```

2023-10-11 14:30 UTC, jllr commented on src/website/views/components/alert/_examples.pug
> +      chi-alert.-m--2(color=type, icon=val, spinner)
@wojciechwlodarczyklumen please remove all the icons in the spinners wc examples as they are not needed. Also check the tests

2023-10-11 14:30 UTC, jllr commented on src/website/views/components/alert/_examples.pug
> +      <chi-alert icon="circle-info" spinner>
```suggestion
      <chi-alert spinner>
```

2023-10-13 09:50 UTC, jllr approved these changes

2023-10-13 09:55 UTC, merged