[DPEDE-834] Added column customization to Modal docs
CenturyLink/Chi pull request #853
Opened 2023-10-27 14:51 UTC by wojciechwlodarczyklumen

https://ctl.atlassian.net/browse/DPEDE-834

2023-10-27 15:08 UTC, josecarlosgonzalezv requested changes

2023-10-27 15:08 UTC, josecarlosgonzalezv commented on src/website/views/components/modal/_examples.pug
> +      }
Why do we need this as it relates to the e2e tests?

2023-10-27 15:08 UTC, josecarlosgonzalezv commented on src/website/views/components/modal/_examples.pug
> +      <ChiColumnCustomization id="column-customization" ref="baseColumnCustomizationRef" :columns-data="columnsData"></ChiColumnCustomization>
```suggestion
      <ChiColumnCustomization id="column-customization" ref="baseColumnCustomizationRef" :columnsData="columnsData"></ChiColumnCustomization>
```

2023-10-27 15:08 UTC, josecarlosgonzalezv commented on src/website/views/components/modal/_examples.pug
> +    ul.chi-tabs#example-no-results
Take care with the IDs

```suggestion
    ul.chi-tabs#example-column-customization-modal
```

2023-10-27 15:08 UTC, josecarlosgonzalezv commented on src/website/views/components/modal/_examples.pug
> +    .chi-tab__description Use <code>columns-data</code> to customize the columns.
```suggestion
    .chi-tab__description Use <code>columnsData</code> to customize the columns.
```

2023-11-03 15:22 UTC, josecarlosgonzalezv approved these changes

2023-11-03 15:22 UTC, josecarlosgonzalezv commented on src/website/views/components/modal/_examples.pug
> +      <ChiColumnCustomization id="column-customization" ref="baseColumnCustomizationRef" :columnsData="columnsData"></ChiColumnCustomization>
```suggestion
      <ChiColumnCustomization :columnsData="columnsData"></ChiColumnCustomization>
```

2023-11-06 12:25 UTC, jllr approved these changes

2023-11-06 12:33 UTC, merged