[DPEDE-885] Add color, variant, size, uppercase and disabled properties to dropdown wc.
CenturyLink/Chi pull request #866
Opened 2023-11-08 11:21 UTC by ASanchLumen

(https://ctl.atlassian.net/browse/DPEDE-885

2023-11-13 10:53 UTC, jllr requested changes

2023-11-13 10:53 UTC, jllr commented on src/custom-elements/src/components/dropdown/dropdown.tsx
> +        center={this.center}
@ASanchLumen this property doesn't exist in dropdown. Jenkins has failed. Could you remove it?

2023-11-13 13:43 UTC, jllr approved these changes

2023-11-14 12:15 UTC, ASanchLumen commented
@jllr @josecarlosgonzalezv Vue documentation refactored!

2023-11-14 18:49 UTC, josecarlosgonzalezv approved these changes

2023-11-15 11:04 UTC, merged