[DPEDE-895]
CenturyLink/Chi pull request #870
Opened 2023-11-13 10:25 UTC by ASanchLumen

https://ctl.atlassian.net/browse/DPEDE-895

- Adds `chiSearchInputItemSelected` event in search-input wc that emits the item clicked
- Adds property `disableItemSelectedEvent` in dropdown wc that disables that event, as it is not working properly when this component is used in search-input wc
- Sets `disable-item-selected-event` in the dropdown used in searc-input wc.

2023-11-13 15:47 UTC, josecarlosgonzalezv requested changes

2023-11-13 15:47 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/dropdown/dropdown.tsx
> +  @Prop() disableItemSelectedEvent = false;
```suggestion
  @Prop() preventItemSelectedEvent = false;
```

2023-11-13 15:47 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/dropdown/dropdown.tsx
> +      });
Same in `_removeEventListeners()`

```suggestion
    if (this.preventItemSelectedEvent) return;
    
    menuItems.forEach((item: HTMLElement) => {
       item.addEventListener('click', this.handlerSelectedMenuItem);
    });
```

2023-11-13 15:47 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/search-input/search-input.tsx
> +  @Event({ eventName: `chiSearchInputItemSelected`}) itemSelected: EventEmitter<DropdownMenuItem>
Single quotes. Is this name correct: `chiSearchInputItemSelected`? @jllr 

```suggestion
  @Event({ eventName: 'chiSearchInputItemSelected'}) eventItemSelected: EventEmitter<DropdownMenuItem>
```

2023-11-13 15:47 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/search-input/search-input.tsx
> -        prevent-auto-hide
Good catch!

2023-11-13 15:47 UTC, josecarlosgonzalezv commented on test/chi/custom-elements/search-input.pug
> +  document.addEventListener('chiDropdownItemSelected', (ev) => console.log("chiDropdownItemSelected", ev.detail));
I don't think it's necessary to include listeners here.

2023-11-13 15:47 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/dropdown/dropdown.tsx
> +  @Event({ eventName: 'chiDropdownItemSelected' }) eventItemSelected: EventEmitter;
Be careful with linting, I would remove all the linting that you have changed.

2023-11-14 09:39 UTC, josecarlosgonzalezv approved these changes

2023-11-14 09:39 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/dropdown/dropdown.tsx
> +    if (this.preventItemSelectedEvent) return
```suggestion
    if (this.preventItemSelectedEvent) return;
```

2023-11-14 09:39 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/dropdown/dropdown.tsx
> +    if (this.preventItemSelectedEvent) return
```suggestion
    if (this.preventItemSelectedEvent) return;
```

2023-11-14 09:39 UTC, josecarlosgonzalezv commented on test/chi/custom-elements/search-input.pug
> +      { title: "Item 5", href: "#"}
```suggestion
      { title: "Item 5", href: "#" }
```

2023-11-14 11:04 UTC, jllr commented on src/custom-elements/src/components/dropdown/dropdown.tsx
> +  @Prop() preventItemSelectedEvent = false;
```suggestion
  @Prop() preventItemSelected = false;
```

2023-11-14 11:04 UTC, jllr commented on src/custom-elements/src/components/dropdown/dropdown.tsx
> +    if (this.preventItemSelectedEvent) return;
```suggestion
    if (this.preventItemSelected) return;
```

2023-11-14 11:04 UTC, jllr commented on src/custom-elements/src/components/dropdown/dropdown.tsx
> +    if (this.preventItemSelectedEvent) return;
```suggestion
    if (this.preventItemSelected) return;
```

2023-11-14 11:04 UTC, jllr commented on src/custom-elements/src/components/search-input/search-input.tsx
> +        disable-item-selected-event
```suggestion
        prevent-item-selected
```

2023-11-14 14:58 UTC, jllr approved these changes

2023-11-14 14:58 UTC, merged