Dpede 409 date picker keyboard functionality
CenturyLink/Chi pull request #874
Opened 2023-11-17 09:54 UTC by ASanchLumen

2023-12-05 08:35 UTC, jllr approved these changes

2023-12-05 11:19 UTC, josecarlosgonzalezv requested changes
You need to pass `prettier` for all files to fix a lot of linting problems.

2023-12-05 11:19 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/date/date.tsx
> +      this._keyboardFocusedDate = this._getValidDayElement(this.value)
```suggestion
      const today = dayjs().format(this.format);
      
      this._keyboardFocusedDate = this._getValidDayElement(this.value);
```

2023-12-05 11:19 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/date/date.tsx
> +      return
```suggestion
      return;
```

2023-12-05 11:19 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/date/date.tsx
> +    // TODO: check if calendar is focused in to enable arrows
Do we need this TODO?

2023-12-05 11:19 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/date/date.tsx
> +    if (!keyHandler || disableArrowHandler || !contains(this.el, e.target as HTMLElement)) {
```suggestion
    const disableArrowHandler = e.key.startsWith("Arrow") && !this._isTargetCalendarDay(e);
    
    if (!keyHandler || disableArrowHandler || !contains(this.el, e.target as HTMLElement)) {
```

2023-12-05 11:19 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/date/date.tsx
> +    return (e.target as HTMLElement).classList.contains("chi-datepicker__day");
Do we have this class in the `classes.ts` file? If not include it and same for the rest.

```suggestion
    return (e.target as HTMLElement).classList.contains(DATEPICKER_DAY);
```

2023-12-05 11:19 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/date/date.tsx
> +    if (shouldMoveMonth) {
```suggestion
    const shouldMoveMonth = this._isDayInRange(dayjs(this._keyboardFocusedDate).add(dayDiff, 'day'));
    
    if (shouldMoveMonth) {
```

2023-12-05 11:19 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/date/date.tsx
> +    const dayToFocus = this._getValidDayElement(nextDateFormatted)
```suggestion
    )?.getAttribute('data-date');
    const dayToFocus = this._getValidDayElement(nextDateFormatted)
```

2023-12-05 11:19 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/date/date.tsx
> +    if (!element) {
```suggestion
    const element = this._getValidDayElement(date);
    
    if (!element) {
```

2023-12-05 11:19 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/date/date.tsx
> +    if (currentElement && currentElement !== element) {
```suggestion
    const currentElement = this._getValidDayElement(this._keyboardFocusedDate);
    
    if (currentElement && currentElement !== element) {
```

2023-12-05 11:19 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/date/date.tsx
> +    return Array.from(availableDays);
```suggestion
    const availableDays = this.el.querySelectorAll('.chi-datepicker__day:not(.-inactive)');
    
    return Array.from(availableDays);
```

2023-12-05 11:19 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/date/date.tsx
> +    const nextElement = e.shiftKey
```suggestion
    tabElements = [...tabElements, ...tabElements].filter(Boolean);

    const nextElement = e.shiftKey
```

2023-12-05 11:19 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/date/date.tsx
> +              }`}
```suggestion
            class={`prev ${prevMonthDisabled ? CLASSES.DISABLED : ''}`}
```

2023-12-05 11:19 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/date/date.tsx
> +            class={`next ${nextMonthDisabled ? CLASSES.DISABLED : ''
Same here

2023-12-05 11:19 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/date/date.tsx
> +            return (
```suggestion
            const isExcludedDay = this.checkIfExcluded(day);
            
            return (
```

2023-12-05 11:19 UTC, josecarlosgonzalezv commented on test/chi/custom-elements/date-picker.pug
> +  span.text--h2 Test keyboard functionality
This text is not similar to the other tests because you've missed one `-`

```suggestion
  span.-text--h2 Test keyboard functionality
```

2023-12-05 13:57 UTC, josecarlosgonzalezv commented on package.json
> +    "prettier": ""
Why add prettier without any command, is it necessary?

2023-12-12 09:04 UTC, ASanchLumen commented
new PR opened: https://github.com/CenturyLink/Chi/pull/903

2023-12-12 09:04 UTC, closed without merging