[DPEDE-913] Add helper message in phone-input
CenturyLink/Chi pull request #882
Opened 2023-11-22 15:21 UTC by ASanchLumen

[JIRA Ticket](https://ctl.atlassian.net/browse/DPEDE-913)

2023-11-24 14:30 UTC, josecarlosgonzalezv requested changes

2023-11-24 14:30 UTC, josecarlosgonzalezv commented on cypress/e2e/chi-custom-elements/phone-input.cy.js
> +    it("Should initiate with helper-message attribute", function() {
```suggestion
    });
    
    it('Should initiate with helper-message attribute', () => {
```

2023-11-24 14:30 UTC, josecarlosgonzalezv commented on cypress/e2e/chi-custom-elements/phone-input.cy.js
> +      cy.get("@phoneInput")
```suggestion
      cy.get('@phoneInput')
```

2023-11-24 14:30 UTC, josecarlosgonzalezv commented on cypress/e2e/chi-custom-elements/phone-input.cy.js
> +      .should('have.class', '-danger');
```suggestion
      cy.get('@phoneInput')
        .find('.chi-label')
        .should('have.class', '-danger');
```

2023-11-24 14:30 UTC, josecarlosgonzalezv commented on cypress/e2e/chi-custom-elements/phone-input.cy.js
> +        .find('chi-helper-message').should('exist');
```suggestion
        .find('chi-helper-message')
        .should('exist');
```

2023-11-24 14:30 UTC, josecarlosgonzalezv commented on cypress/e2e/chi-custom-elements/phone-input.cy.js
> +      cy.get('@phoneInput').find('chi-icon')
```suggestion
      cy.get('@phoneInput')
        .find('chi-icon')
```

2023-11-27 08:13 UTC, jllr approved these changes

2023-11-27 09:24 UTC, josecarlosgonzalezv requested changes

2023-11-27 09:24 UTC, josecarlosgonzalezv commented on cypress/e2e/chi-custom-elements/phone-input.cy.js
> +    it("Should initiate with helper-message attribute", () => {
```suggestion
    });
    
    it("Should initiate with helper-message attribute", () => {
```

2023-11-27 09:24 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/phone-input/phone-input.tsx
> +   * To display an additional helper text message below the Textarea
Textarea?

```suggestion
   * To display an additional helper text message below the Phone input
```

2023-11-27 12:08 UTC, josecarlosgonzalezv approved these changes

2023-11-27 12:56 UTC, merged