[DPEDE-334] Fix autocomplete serach input on filtering
CenturyLink/Chi pull request #888
Opened 2023-11-23 19:14 UTC by wojciechwlodarczyklumen

2023-11-24 09:10 UTC, josecarlosgonzalezv requested changes

2023-11-24 09:10 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/dropdown/dropdown.tsx
> +    observer.observe(this._dropdownMenuElement, { childList: true });
```suggestion
    const observer = new MutationObserver(() => this.setMenuHeight());
    
    observer.observe(this._dropdownMenuElement, { childList: true });
```

2023-11-27 09:14 UTC, jllr approved these changes

2023-11-27 09:25 UTC, josecarlosgonzalezv approved these changes

2023-11-27 09:33 UTC, merged