[FSDE-1073] Fixed Data Table sorting of negative numbers issue
CenturyLink/Chi pull request #90
Opened 2021-07-01 20:53 UTC by janibolkvadze

https://ctl.atlassian.net/browse/FSDE-1073

2021-07-01 21:17 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-90/1/. :white_check_mark:

2021-07-01 21:17 UTC, SCMAUTO commented
You can check this PRs instance in https://d1d6de294a05954df944ea9fa37fcf2e276801f4-chi-pr.enterprise.ctl.io

2021-07-02 08:08 UTC, jllr approved these changes

2021-07-02 08:58 UTC, SergioQCL requested changes

2021-07-02 08:58 UTC, SergioQCL commented on src/chi-vue/src/constants/types.ts
> +  };
Are they all mandatory?

2021-07-02 08:58 UTC, SergioQCL commented on src/chi-vue/src/components/data-table/DataTable.tsx
> +        }
```suggestion
        this.resultsPerPage = (ev=== 'all') ? this._serializedDataBody.length : parseInt(ev);
```

2021-07-02 08:58 UTC, SergioQCL commented on src/chi-vue/src/components/data-table/DataTable.tsx
> +          sortBy && a.data[columnIndex].payload[sortBy] ? a.data[columnIndex].payload[sortBy] : a.data[columnIndex];
Would it make sense to create a small function for this?

2021-07-02 08:58 UTC, SergioQCL commented on src/chi-vue/src/components/data-table/DataTable.tsx
> +          debugger;
Please remove

2021-07-02 09:04 UTC, dani-cl-madrid approved these changes

2021-07-02 09:04 UTC, dani-cl-madrid commented on src/chi-vue/src/components/data-table/DataTable.tsx
> +          data: this.slicedData,
If mode is serverSidePaginated, data should be empty. I guess it will be empty indeed, right?

2021-07-02 09:13 UTC, dani-cl-madrid commented on src/chi-vue/src/components/data-table/DataTable.tsx
> +          data: this.slicedData,
@janibolkvadze explained me and it works as expected. Thanks Jani.

2021-07-02 10:00 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-90/2/. :x:

2021-07-02 10:09 UTC, SergioQCL approved these changes
ACK

2021-07-02 10:58 UTC, aryaroudi approved these changes

2021-07-02 11:26 UTC, SCMAUTO commented
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-90/3/. :x:

2021-07-02 11:51 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-90/4/. :white_check_mark:

2021-07-02 11:51 UTC, SCMAUTO commented
You can check this PRs instance in https://97daeb1647d1384f29263a8bbb90599f6c1644cc-chi-pr.enterprise.ctl.io

2021-07-02 14:12 UTC, SCMAUTO commented
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-90/6/. :white_check_mark:

2021-07-02 14:12 UTC, SCMAUTO commented
You can check this PRs instance in https://97daeb1647d1384f29263a8bbb90599f6c1644cc-chi-pr.enterprise.ctl.io

2021-07-02 15:06 UTC, merged