[DPEDE-1124] Added font weight prop to dropdown, added tests
CenturyLink/Chi pull request #908
Opened 2023-12-18 16:04 UTC by wojciechwlodarczyklumen

https://ctl.atlassian.net/browse/DPEDE-1124

2023-12-19 09:19 UTC, josecarlosgonzalezv requested changes

2023-12-19 14:47 UTC, josecarlosgonzalezv requested changes

2023-12-19 14:47 UTC, josecarlosgonzalezv commented on src/custom-elements/src/components/dropdown/dropdown.tsx
> +type FontWeight = 'normal';
Move it to the `constants.ts` file

2023-12-28 10:13 UTC, josecarlosgonzalezv approved these changes

2023-12-28 10:19 UTC, jllr approved these changes

2023-12-28 10:23 UTC, merged