[DPEDE-1179] Reusable mutationObserver and implementation in chi-alert
CenturyLink/Chi pull request #934
Opened 2024-01-10 14:41 UTC by ASanchLumen

https://ctl.atlassian.net/browse/DPEDE-1179

2024-01-10 16:59 UTC, josecarlosgonzalezv requested changes

2024-01-10 16:59 UTC, josecarlosgonzalezv commented on cypress/e2e/chi-custom-elements/alert.cy.js
> +    it('should change displayed title if attribute changes', () => {
```suggestion
    it('Should change displayed title if attribute changes', () => {
```

2024-01-10 16:59 UTC, josecarlosgonzalezv commented on cypress/e2e/chi-custom-elements/alert.cy.js
> +        .find('.chi-alert__title')
Use constant class here: `ALERT_TITLE`

```suggestion
        .find(`.${ALERT_TITLE}`)
```

2024-01-11 09:36 UTC, josecarlosgonzalezv approved these changes

2024-01-11 15:58 UTC, jllr approved these changes

2024-01-11 16:11 UTC, merged