[DPEDE-1225] Add large header option to portal
CenturyLink/Chi pull request #959
Opened 2024-01-19 15:30 UTC by emerson-pereira

2024-01-19 15:41 UTC, emerson-pereira commented
@jllr @josecarlosgonzalezv

Need advise:

- for portal, header were already large size, I set all header to base size and set the new one only to large
- regarding the dropdown menus, there's no option to remove chevron

2024-01-19 18:17 UTC, emerson-pereira commented
> @jllr @josecarlosgonzalezv
> 
> Need advise:
> 
> * for portal, header were already large size, I set all header to base size and set the new one only to large
> * regarding the dropdown menus, there's no option to remove chevron

- Confirmed all headers should be large for portal
- Dropdown menu styles applied

2024-01-30 18:05 UTC, jllr requested changes
Also, a visual test for lg size with dropdown menu should be created (similar to this: XL Header with Navbar)

2024-01-30 18:05 UTC, jllr commented on src/chi/components/header/header.scss
> +      }
```suggestion
  &.-xl {
    .chi-header__navbar {
      .chi-tabs {
        &:not(.-vertical) {
          &.-sm {
            &:not(.-vertical):not(.-responsive) {
              height: 3rem;
            }
          }
        }
      }
```

2024-01-30 18:05 UTC, jllr commented on src/chi/components/header/header.scss
> +                padding: 1rem 0;
```suggestion
                padding: 0.5rem 0;
```

2024-02-01 11:52 UTC, emerson-pereira commented
> Also, a visual test for lg size with dropdown menu should be created (similar to this: XL Header with Navbar)

@jllr Visual test created

2024-02-01 15:20 UTC, jllr commented
@emerson-pereira I will chek the chevron update when the PR builds. Thanks!

2024-02-05 10:46 UTC, jllr commented on src/chi/components/header/header.scss
> +          &::before {
&:before must be on dropdown__menu selector and not target to menu items. It is causing it renders several times

2024-02-05 10:56 UTC, jllr requested changes
Also change to xs size in tabs to reflect the same size we have in Lumen example. Then the tests will be fine

2024-02-05 13:01 UTC, emerson-pereira commented on test/chi/components/header.pug
> +          ul.chi-tabs.-inverse.-sm.-animated
@jllr done

2024-02-05 16:24 UTC, josecarlosgonzalezv approved these changes

2024-02-05 16:26 UTC, jllr approved these changes

2024-02-06 08:55 UTC, merged